
shushi_currencies = {
    # 835个，但有二个 'yyDAI+yUSDC+yUSDT+yTUSD', '⚗️' 没有加上
    "ethereum":{
        "TBTC":"tBTC", '$DG': 'decentral.games', '$MAID': 'MaidCoin', '$TRDL': 'Strudel Finance', '0xBTC': '0xBitcoin Token','ETH': 'Ether', 
        '1INCH': '1INCH Token', '1ONE': 'Harmony ONE', 'AAVE': 'Aave Token', 'ACH': 'Alchemy', 'ACX': 'Across Protocol Token',
        'ADX': 'AdEx Network', 'AERGO': 'Aergo', 'agEUR': 'agEUR', 'AGIX': 'SingularityNET Token', 'AGLD': 'Adventure Gold',
        'AIOZ': 'AIOZ Network', 'AIUS': 'Arbius', 'AKITA': 'Akita Inu', 'AKRO': 'Akropolis', 'ALBT': 'AllianceBlock Token',
        'ALCX': 'Alchemix', 'ALD': 'Aladdin Token', 'ALEPH': 'aleph.im v2', 'ALICE': 'ALICE', 'ALPA': 'AlpaToken',
        'ALPHA': 'AlphaToken', 'alUSD': 'Alchemix USD', 'aMATICc': 'Ankr MATIC Reward Bearing Certificate', 'AMP': 'Amp', 'AMPL': 'Ampleforth',
        'ANGLE': 'ANGLE', 'ANKR': 'Ankr Network', 'ankrETH': 'Ankr Staked ETH', 'ANT': 'Aragon Network Token', 'ANY': 'Anyswap',
        'APE': 'ApeCoin', 'API3': 'API3', 'APW': 'APWine Token', 'APY': 'APY Governance Token', 'ARB': 'Arbitrum',
        'ARCH': 'Archer DAO Governance Token', 'ARCONA': 'Arcona Distribution Contract', 'ARCX': 'ARCx Governance Token', 'ARMOR': 'Armor', 'arNXM': 'Armor NXM',
        'ARPA': 'ARPA Token', 'ASH': 'Burn', 'ASM': 'ASSEMBLE', 'ASSY': 'ASSY Index', 'AST': 'AirSwap Token',
        'ASTRAFER': 'Astrafer', 'ATRI': 'AtariToken', 'ATTR': 'Attrace', 'Auction': 'Bounce Token', 'AUDIO': 'Audius',
        'axlTIA': 'Axelar Wrapped TIA', 'AXS': 'Axie Infinity Shard', 'BAB': 'BAB', 'BAC': 'BAC', 'BACON': 'BaconCoin',
        'BADGER': 'Badger', 'BAL': 'Balancer', 'BANANA': 'Banana', 'BAND': 'BandToken', 'BANK': 'Float Bank',
        'BAO': 'BaoToken', 'BASE': 'Base Protocol', 'BASK': 'BasketDAO Gov', 'BAT': 'Basic Attention Token', 'bBADGER': 'Badger Sett Badger',
        'BBANK': 'BlockBank', 'BCP': 'PieDAO Balanced Crypto Pie', 'bDIGG': 'Badger Sett Digg', 'BDP': 'BDPToken', 'bDPI': 'Interest Bearing Defi Pulse Index',
        'BEL': 'Bella', 'BEND': 'Bend Token', 'BENT': 'Bent Token', 'BEPRO': 'BetProtocolToken', 'BFC': 'Bifrost',
        'BGLD': 'Based Gold', 'BICO': 'Biconomy Token', 'BID': 'Bidao', 'BiFi': 'BiFi', 'BIOS': 'BIOS',
        'BIRD': 'Bird.Money', 'BIT': 'BitDAO', 'BLANK': 'GoBlank Token', 'BLOCK': 'Block', 'BLOCKS': 'BLOCKS',
        'BLUR': 'Blur', 'BLZ': 'Bluzelle Token', 'BMI': 'Bridge Mutual', 'BNPL': 'BNPL Pay', 'BNT': 'Bancor Network Token',
        'BOB': 'BOB', 'BOND': 'BarnBridge Governance Token', 'BONDLY': 'Bondly', 'BONE': 'BONE SHIBASWAP', 'BOR': 'BoringDAO',
        'BOSON': 'Boson Token', 'BOTTO': 'Botto', 'BPT': 'BlackPool Token', 'BSGG': 'Betswap.gg', 'BTC2x-FLI': 'BTC 2x Flexible Leverage Index',
        'BTM': 'Bytom', 'BTRFLY': 'BTRFLY', 'BTSE': 'BTSE Token', 'BTT': 'BitTorrent', 'BUND': 'Bundles',
        'BUSD': 'Binance USD', 'BZRX': 'bZx Protocol Token', 'C98': 'Coin98', 'CAPS': 'Capsule Coin', 'CARDS': 'CARD.STARTER',
        'CAW': 'A Hunters Dream', 'cbETH': 'Coinbase Wrapped Staked ETH', 'cDAI': 'Compound Dai', 'CEL': 'Celsius', 'CELL': 'Cellframe Token',
        'CELO': 'Celo native asset', 'CELR': 'CelerToken', 'CFi': 'CyberFi Token', 'CGG': 'ChainGuardians Governance Token', 'CHAIN': 'Chain Games' ,    
        'CHEESE': 'CheeseFry', 'CHSB': 'SwissBorg Token', 'CHZ': 'chiliZ', 'CIG': 'Cigarette Token', 'CIV': 'Civilization',
        'CLNY': 'Colony Network Token', 'CLV': 'Clover', 'CMK': 'Credmark', 'CNDL': 'Candle', 'COMBO': 'Furucombo',
        'COMP': 'Compound', 'COOK': 'Cook Token', 'COOL': 'Cool Cats', 'COTI': 'COTI Token', 'Coval': 'CircuitsOfValue',
        'COVER': 'Cover Protocol Governance Token', 'COW': 'CoW Protocol Token', 'CPRX': 'Crypto Perx', 'CQT': 'Covalent Query Token', 'CRD': 'CryptalDash',
        'CRE8': 'Creaticles', 'CREAM': 'Cream', 'CRETH2': 'Cream ETH 2', 'CRO': 'CRO', 'CRPT': 'CRPT',
        'CRU': 'CRUST', 'CRV': 'Curve DAO Token', 'CTSI': 'Cartesi Token', 'CTX': 'Cryptex', 'CULT': 'Cult DAO',
        'CVC': 'Civic', 'CVP': 'Concentrated Voting Power', 'CVR': 'PolkaCover', 'CVX': 'Convex Token', 'cvxCRV': 'Convex CRV',
        'CWS': 'Crowns', 'DAFI': 'DAFI Token', 'DAI': 'Dai Stablecoin', 'DAM': 'Datamine', 'DAO': 'DAO Maker',
        'DAOX': 'The DAOX Index', 'DATA': 'DATA Economy Index', 'DDIM': 'DuckDaoDime', 'DDX': 'DerivaDAO', 'DEC': 'DarkEnergyCrystals',
        'DEFI+L': 'PieDAO DEFI Large Cap', 'DEGEN': 'DEGEN Index', 'DELTA': 'DELTA.financial - deep DeFi derivatives', 'DENT': 'DENT', 'DERC': 'DeRace Token',
        'DERI': 'Deri', 'DEV': 'Dev', 'DEXT': 'DEXTools', 'DEXTF': 'DEXTF Token', 'DFD': 'DefiDollar DAO',
        'DFX': 'DFX Token', 'DGTX': 'DigitexFutures', 'DIA': 'DIAToken', 'DIGG': 'Digg', 'DIP': 'Decentralized Insurance Protocol',
        'DIVER': 'DivergenceProtocol', 'DIVINE': 'divinedao', 'DN': 'Deez Nuts', 'DNT': 'district0x Network Token', 'DODO': 'DODO bird',
        'DOG': 'The Doge NFT', 'DOLA': 'Dola USD Stablecoin', 'DON': 'Donkey', 'DOSE': 'DOSE', 'DOUGH': 'PieDAO DOUGH v2',
        'DOV': 'DOVU', 'DPI': 'DefiPulse Index', 'DPR': 'Deeper Network', 'DPX': 'Dopex Governance Token', 'DRC': 'Digital Reserve Currency',
        'DSD': 'Dynamic Set Dollar', 'dsETH': 'Diversified Staked ETH Index (dsETH)', 'DSLA': 'DSLA', 'DUCK': 'Unit Protocol', 'DUSD': 'DefiDollar' , 
        'DVF': 'DeversiFi Token', 'DWEB': 'DecentraWeb', 'DYDX': 'dYdX', 'DYP': 'DeFiYieldProtocol', 'EDDA': 'EDDA',
        'EDEN': 'Eden', 'EGT': 'Elastic Governance', 'EJS': 'Enjinstarter', 'ELF': 'ELF Token', 'ELON': 'Dogelon',
        'EMT': 'Emanate', 'eMTRG': 'Meter Governance mapped by Meter.io', 'ENJ': 'Enjin Coin', 'ENS': 'Ethereum Name Service', 'ENTR': 'ENTER Governance Token',
        'EPAN': 'Paypolitan Token', 'EPIK': 'Epik Prime', 'ERN': '@EthernityChain $ERN Token', 'erowan': 'erowan', 'eRSDL': 'UnFederalReserveToken' ,
        'ESD': 'Empty Set Dollar', 'ETH2x-FLI': 'ETH 2x Flexible Leverage Index', 'ETHC': 'ETH Coin', 'EUROC': 'Euro Coin', 'EUROe': 'EUROe Stablecoin',
        'EWTB': 'Energy Web Token Bridged', 'eXRD': 'E-RADIX', 'FARM': 'FARM Reward Token', 'FCL': 'Fractal Protocol Token', 'FEAR': 'Fear NFTs',
        'FEI': 'Fei USD', 'FET': 'Fetch', 'fFRAX': 'Fluid FRAX', 'FLEX': 'FLEX Coin', 'FLOAT': 'Float Protocol: FLOAT',
        'FLOKI': 'FLOKI', 'FLUX': 'FLUX', 'FLX': 'Flux Token', 'FNC': 'Fancy Games', 'FNX': 'FinNexus',
        'FOAM': 'FOAM Token', 'FODL': 'Fodl', 'FOLD': 'Manifold Finance', 'FONT': 'Font', 'FORTH': 'Ampleforth Governance',
        'FOX': 'FOX', 'FRAX': 'Frax', 'FRM': 'Ferrum Network Token', 'FRONT': 'Frontier Token', 'FTM': 'Fantom Token',
        'FTX Token': 'FTT', 'FUN': 'FunFair', 'fUSDC': 'Fluid USDC', 'fUSDT': 'Fluid USDT', 'FUSE': 'Fuse Token',
        'FWB': 'Friends With Benefits Pro', 'FX': 'Function X', 'FXS': 'Frax Share', 'G$': 'GoodDollar', 'GALA': 'Gala',
        'GAME': 'Game Coin', 'GANG': 'GANG', 'GAS': 'Gas DAO', 'GDAO': 'Governor', 'GEEQ': 'Geeq',
        'GENE': 'GenomesDAO', 'GERO': 'GeroWallet', 'GET': 'GET', 'GFARM2': 'Gains V2', 'GFI': 'Goldfinch',
        'GHST': 'Aavegotchi GHST Token', 'GLCH': 'Glitch', 'GLM': 'Golem Network Token', 'GLQ': 'GraphLinq', 'gm': 'we love gm',
        'GMEE': 'GAMEE', 'GMI': 'Bankless DeFi Innovation Index', 'GNO': 'Gnosis Token', 'GODS': 'Gods Unchained', 'GOG': 'Guild of Guardians',
        'gOHM': 'Governance OHM', 'GOVI': 'GOVI', 'GRID': 'GRID Token', 'GRT': 'Graph Token', 'GSWAP': 'gameswap.org',
        'GTC': 'Gitcoin', 'gtcETH': 'Gitcoin Staked ETH Index (gtcETH)', 'GTON': 'Graviton', 'GUILD': 'BlockchainSpace', 'GUSD': 'Gemini dollar',
        'GYEN': 'GMO JPY', 'GYSR': 'Geyser', 'HBTC': 'Huobi BTC', 'HDRN': 'Hedron', 'HEGIC': 'Hegic',
        'HEX': 'HEX', 'HEZ': 'Hermez Network Token', 'HIGH': 'Highstreet token', 'HND': 'Hundred Finance', 'HOGE': 'hoge.finance',
        'HOP': 'Hop', 'HOPR': 'HOPR Token', 'HORD': 'HORD Token', 'HOT': 'HoloToken', 'HPO': 'Hippopotamus',
        'HT': 'HuobiToken', 'HUSD': 'HUSD', 'ibBTC': 'Interest-Bearing BTC', 'ibETHv2': 'Interest Bearing Ether v2', 'IBY': 'I Bet You',
        'ICE': 'IceToken', 'ICHI': 'ichi.farm', 'ID': 'Everest ID', 'IDLE': 'Idle', 'ILSI': 'Invest Like Stakeborg Index',
        'ILV': 'Illuvium', 'IMX': 'Immutable X', 'INDEX': 'Index', 'INJ': 'Injective Token', 'INST': 'Instadapp',
        'INSUR': 'InsurAce', 'INV': 'Inverse DAO', 'IONX': 'Charged Particles - IONX', 'IOST': 'IOST', 'IOTX': 'IoTeX Network',
        'IQ': 'Everipedia IQ', 'ITP': 'Interport Token', 'IXS': 'Ixs Token', 'JACY': 'JACY', 'JASMY': 'JasmyCoin',
        'jCHF': 'Jarvis Synthetic Swiss Franc', 'JELLY': 'Jelly Token', 'jEUR': 'Jarvis Synthetic Euro', 'jim': 'jim', 'JPEG': 'JPEG’d Governance Token' , 
        'JPYC': 'JPY Coin', 'JRT': 'Jarvis Reward Token', 'JUP': 'Jupiter', 'JUSTICE': 'AssangeDAO', 'KAE': 'Kanpeki',
        'KEEP': 'KEEP Token', 'KEX': 'KIRA Network', 'KINE': 'Kine Governance Token', 'KIRA': 'KIRA', 'KIRO': 'Kirobo',
        'KISHU': 'Kishu Inu', 'KKO': 'Kineko', 'KNC': 'Kyber Network Crystal', 'KOIN': 'Koinos', 'KOMPETE': 'KOMPETE Token',
        'KONO': 'Konomi', 'KP3R': 'Keep3rV1', 'KRL': 'Kryll', 'KROM': 'Kromatika', 'KUMA': 'Kuma Inu',
        'LAYER': 'Unilayer', 'LCX': 'LCX', 'LDN': 'Ludena Protocol', 'LDO': 'Lido DAO Token', 'LEAG': 'LeagueDAO Governance Token',
        'LEASH': 'DOGE KILLER', 'LEND': 'EthLend Token', 'LEV': 'Lever Token', 'LEVX': 'LevX DAŌh..Geez', 'LGCY': 'LGCY Network',
        'LINA': 'Linear Token', 'LINK': 'ChainLink Token', 'LKR': 'Polkalokr', 'LOBI': 'Lobi', 'LON': 'Tokenlon',
        'LOOKS': 'LooksRare Token', 'LOOM': 'LoomToken', 'LPOOL': 'Launchpool token', 'LPT': 'Livepeer Token', 'LQTY': 'LQTY',
        'LRC': 'LoopringCoin V2', 'LSD': 'Bad Trip', 'LSS': 'Lossless Token', 'LTX': 'Lattice Token', 'LUFFY': 'LUFFY',
        'LUSD': 'LUSD Stablecoin', 'LYRA': 'Lyra Token', 'LYXe': 'LUKSO Token', 'MAGIC': 'MAGIC', 'MAI': 'Mai Stablecoin',
        'MAMZN': 'Mirrored Amazon', 'MANA': 'Decentraland MANA', 'Mars': 'MarsToken', 'MARS4': 'MARS4', 'MARSH': 'UnmarshalToken',
        'MASK': 'Mask Network', 'MASQ': 'MASQ', 'MATIC': 'Matic Token', 'mbBASED': 'Moonbase', 'mBTC': 'mStable BTC',
        'MC': 'Merit Circle', 'MCO2': 'Moss Carbon Credit', 'MDT': 'Measurable Data Token', 'MEDIA': 'Media Network Token', 'MEEB': 'Meebits',
        'MEME': 'MEME', 'MEOW': 'Meowshi', 'MetaCat': 'MetaCat', 'Metis': 'Metis Token', 'MEZZ': 'MEZZ Token',
        'MFB': 'Mirrored Facebook', 'MFG': 'SyncFab Smart Manufacturing Blockchain', 'MGOOGL': 'M Google', 'MIC': 'MIC', 'MILADY': 'Milady Maker',
        'MIM': 'Magic Internet Money', 'MINDS': 'Minds', 'MINT': 'Public Mint', 'MIR': 'Wrapped MIR Token', 'MIS': 'MIS',
        'MITx': 'Morpheus Infrastructure Token', 'MKR': 'Maker', 'MLN': 'Melon Token', 'MM': 'Million', 'MMSFT': 'Mirrored Microsoft',
        'MOD': 'Modefi', 'MODA': 'moda', 'MONA': 'Monavale', 'MOONEY': 'MOONEY', 'MPH': '88mph.app',
        'MPL': 'Maple Token', 'mQQQ': 'Wrapped Mirror QQQ Token', 'MSLV': 'Mirrored iShares Si', 'MTA': 'Meta', 'MTLX': 'Mettalex',
        'MTSLA': 'Mirrored Tesla', 'MULTI': 'Multichain', 'mUSD': 'mStable USD', 'MUSE': 'Muse', 'MUSH': 'MUSH',
        'MUSO': 'M US Oil', 'MUST': 'Must', 'MVI': 'Metaverse Index', 'MVIXY': 'Mirrored ProShares', 'MXC': 'MXCToken',
        'MYST': 'Mysterium', 'NAOS': 'NAOSToken', 'NBT': 'NIX Bridge Token', 'NCR': 'Neos Credits', 'NCT': 'NameChangeToken',
        'NDX': 'Indexed', 'NEAR': 'NEAR', 'NEWO': 'New Order', 'NEWS': 'Newsly', 'NEXO': 'Nexo',
        'NFD': 'Feisty Doge NFT', 'NFP': 'New Frontier Presents', 'NFT': 'NFT Protocol', 'NFTE': 'NFTEarthOFT', 'NFTL': 'Nifty League',
        'NFTX': 'NFTX', 'NIF': 'Unifty', 'NII': 'Nahmii', 'NIL': 'nil', 'NIOX': 'Autonio',
        'NKN': 'NKN', 'NMR': 'Numeraire', 'NOIA': 'NOIA Token', 'NORD': 'Nord Token', 'NPM': 'Neptune Mutual',
        'NPXS': 'Pundi X Token', 'NRCH': 'EnreachDAO', 'NSBT': 'Neutrino System Base Token', 'NST': 'Ninja Squad Token', 'Nsure': 'Nsure Network Token',   
        'NTX': 'NuNet Utility Token', 'NU': 'NuCypher', 'NUM': 'NUM Token', 'O3': 'O3 Swap Token', 'OCC': 'OCC',
        'OCEAN': 'Ocean Token', 'ODDZ': 'OddzToken', 'OETH': 'Origin Ether', 'OGN': 'OriginToken', 'OH-GEEZ': 'Oh..Geez',
        'OHM': 'Olympus', 'OIL': 'Oiler', 'OM': 'MANTRA DAO', 'OMG': 'OMGToken', 'OMNI': 'OmniCat',
        'oneBTC': 'oneBTC', 'oneWING': 'oneWING', 'ONX': 'OnX.finance', 'OOKI': 'Ooki Token', 'OPIUM': 'Opium Governance Token',
        'OPUL': 'OpulousToken', 'ORAI': 'Oraichain Token', 'ORION': 'Orion Money Token', 'ORN': 'Orion Protocol', 'OS': 'Ethereans',
        'oSQTH': 'Opyn Squeeth', 'OUSD': 'Origin Dollar', 'OVR': 'OVR', 'OXT': 'Orchid', 'PAD': 'NearPad Token',
        'PAID': 'PAID Network', 'PAX': 'Paxos Standard', 'PAXG': 'Paxos Gold', 'pBTC35A': 'POW BTC-35W/T', 'PEAK': 'PEAKDEFI',
        'PECO': 'Wrapped PECO', 'PENDLE': 'Pendle', 'PEOPLE': 'ConstitutionDAO', 'PEPE': 'Pepe', 'PERC': 'Perion Credits',
        'PERP': 'Perpetual', 'pETH18C': 'POW ETH-1.8W/M', 'PHA': 'Phala', 'PHTR': 'Phuture', 'PICKLE': 'PickleToken',
        'PILOT': 'Unipilot', 'PIPT': 'Power Index Pool Token', 'PIXEL': 'Pixel', 'PKF': 'PolkaFoundry', 'PLA': 'PlayDapp Token',
        'PLAY': 'Metaverse NFT Index', 'PLOT': 'PLOT', 'PLU': 'Pluton', 'PLUG': 'Pl^g Token', 'PMON': 'Polkamon',
        'PNK': 'Pinakion', 'PNT': 'pNetwork Token', 'POLK': 'Polkamarkets', 'POLS': 'PolkastarterToken', 'POLY': 'Polymath',
        'POND': 'Marlin POND', 'pONT': 'Poly Ontology Token', 'POOL': 'PoolTogether', 'POOLZ': '$Poolz Finance', 'POWR': 'PowerLedger',
        'PPAY': 'Plasma', 'PRE': 'Presearch', 'PREMIA': 'Premia', 'PRIMATE': 'PRIMATE', 'PROS': 'Prosper',
        'PRQ': 'Parsiq Token', 'PRT': 'Portion Token', 'PSP': 'ParaSwap', 'PSWAP': 'Polkaswap', 'PTF': 'PowerTrade Fuel Token',
        'PUDGY': 'Pudgy Penguins', 'PUNDIX': 'Pundi X Token', 'PUNK': 'CryptoPunks', 'PUSH': 'Ethereum Push Notification Service', 'PUSSY': 'PUSSY token' ,
        'pWING': 'Poly Ontology Wing Token', 'QNT': 'Quant', 'QSP': 'Quantstamp Token', 'QUAD': 'Quadency Token', 'QUARTZ': 'Sandclock',
        'QUICK': 'Quickswap', 'RAD': 'Radicle', 'RADAR': 'DappRadar', 'RAI': 'Rai Reflex Index', 'RAIL': 'Rail',
        'RAIN': 'Rainmaker Games', 'RAINI': 'Rainicorn', 'RAMP': 'RAMP DEFI', 'RARE': 'SuperRare', 'RARI': 'Rarible',
        'RAY': 'Raydium', 'RBN': 'Ribbon', 'rDPX': 'Dopex Rebate Token', 'RDT': 'Ridotto', 'REEF': 'Reef.finance',
        'REMIO': 'Remilio Babies', 'REN': 'Republic Token', 'renBCH': 'renBCH', 'renBTC': 'renBTC', 'renDGB': 'renDGB',
        'renDOGE': 'renDOGE', 'renLUNA': 'renLUNA', 'renZEC': 'renZEC', 'REP': 'Reputation', 'REPv2': 'Reputation',
        'REQ': 'Request Token', 'rETH': 'Rocket Pool ETH', 'REVV': 'REVV', 'RFD': 'REFUND', 'RFOX': 'RFOX',
        'RFuel': 'Rio Fuel Token', 'RGT': 'Rari Governance Token', 'RING': 'Darwinia Network Native Token', 'RIO': 'Realio Network', 'RLC': 'iEx.ec Network Token',
        'RLY': 'Rally', 'RND': 'random', 'RNDR': 'Render Token', 'ROOK': 'ROOK', 'ROUTE': 'Route',
        'RULER': 'Ruler Protocol', 'RUNE': 'THORChain ETH.RUNE', 'SAFE': 'Safe Token', 'SAK3': 'Sake', 'SAND': 'SAND',
        'SARCO': 'Sarcophagus', 'SATA': 'Signata', 'sCEX': 'Synth sCEX', 'SDAO': 'Singularity Dao', 'sDEFI': 'Synth sDEFI',
        'SDL': 'stake.link', 'SDT': 'Stake DAO Token', 'SEEN': 'seen.haus', 'sETH2': 'StakeWise Staked ETH2', 'SFI': 'Spice',
        'SHIB': 'SHIBA INU', 'SHIT': 'ShitCoin', 'SHOPX': 'SPLYT SHOPX', 'SHPING': 'Shping Coin', 'SHR': 'ShareToken',
        'SHROOM': 'shroom.finance', 'SHX': 'Stronghold SHx', 'SI': 'SIREN', 'Silo': 'Silo Governance Token', 'sILV2': 'Escrowed Illuvium 2',
        'SIPHER': 'Sipher Token', 'SIS': 'Symbiosis', 'Skey': 'SmartKey', 'SKL': 'SKALE', 'SKYRIM': 'Skyrim Finance',
        'SLP': 'Smooth Love Potion', 'SMARTCREDIT': 'SMARTCREDIT Token', 'SNT': 'Status Network Token', 'SNTVT': 'Sentivate', 'SNX': 'Synthetix Network Token',
        'SOCKS': 'Unisocks Edition 0', 'SOS': 'SOS', 'SOURCE': 'Source', 'SPANK': 'SPANK', 'SPC': 'SpaceChainV2',
        'SPELL': 'Spell Token', 'SPS': 'Splintershards', 'SQGL': 'Chromie Squiggle', 'SQUID': 'Squid', 'SRK': 'SparkPoint',
        'SRM': 'Serum', 'STAK': 'Jigstack', 'STAKE': 'STAKE', 'STANDARD': 'Stakeborg Standard', 'STAR': 'Star',
        'STARL': 'StarLink', 'STARS': 'Mogul Stars', 'stETH': 'Liquid staked Ether 2.0', 'STG': 'StargateToken', 'stkATOM': 'pSTAKE Staked ATOM',
        'stkXPRT': 'Persistence Staked XPRT', 'STMX': 'StormX', 'STND': 'Standard', 'STORJ': 'StorjToken', 'STRK': 'Strike Token',
        'STRNGR': 'Stronger', 'STRONG': 'Strong', 'STRP': 'Strips Token', 'STZ': '99Starz', 'stZEN': 'stakedZEN',
        'SUDO': 'Sudo Governance Token', 'SUKU': 'SUKU', 'SUNC': 'Sunrise Token', 'Sunder': 'Sunder Goverance Token', 'SUPER': 'SuperFarm',
        'sUSD': 'Synth sUSD', 'SUSH': 'Sushimi', 'SUSHI': 'SushiToken', 'SWAG': 'Swag Token', 'SWAP': 'TrustSwap Token',
        'SX': 'SportX', 'SXP': 'Swipe', 'sXRP': 'Synth XRP', 'SYLO': 'Sylo', 'SYN': 'Synapse',
        'SYNC': 'SYNC', 'tBTC': 'tBTC', 'TCR': 'Tracer', 'TEL': 'Telcoin', 'TEMPLE': 'Temple',
        'TGBP': 'TrueGBP', 'TGT': 'THORWallet Governance Token', 'THOR': 'THORSwap Token', 'TIDAL': 'Tidal Token', 'TKING': 'Tiger King',
        'TLOS': 'pTokens TLOS', 'TOK': 'TOK', 'TOKE': 'Tokemak', 'TOMOE': 'TomoChain', 'TORN': 'TornadoCash',
        'TOWER': 'TOWER', 'TOWN': 'TownCoin', 'TRAC': 'Trace Token', 'TRB': 'Tellor Tributes', 'TRIBE': 'Tribe',
        'TRU': 'TrustToken', 'TRX': 'TRON', 'TRY': 'TRYfinance', 'TUSD': 'TrueUSD', 'TVK': 'Terra Virtua Kolect',
        'TWO': 'TwoCoin', 'TXL': 'Tixl Token', 'UBI': 'Universal Basic Income', 'UBT': 'UniBright', 'UBXT': 'UpBots',
        'UDO': 'Unido', 'UDT': 'Unlock Discount Token', 'UFO': 'THE TRUTH', 'UFT': 'UniLend Finance Token', 'UMA': 'UMA Voting Token v1',
        'UMB': 'Umbrella', 'UNCX': 'UniCrypt', 'UNFI': 'UNFI', 'UNI': 'Uniswap', 'UNIBOT': 'Unibot',
        'uniETH': 'Universal ETH', 'UNN': 'UNION Protocol Governance Token', 'UNO': 'UnoRe', 'unshETH': 'unshETH Ether', 'UOP': 'Utopia Open Platform' ,
        'UOS': 'Ultra Token', 'UPI': 'Pawtocol Network UPI Token', 'USDC': 'USD Coin', 'USDN': 'Neutrino USD', 'USDP': 'USDP Stablecoin',
        'USDT': 'Tether USD', 'USDV': 'USDV', 'USH': 'unshETHing_Token', 'UST': 'Wrapped UST Token', 'USV': 'Universal Store of Value',
        'UTK': 'Utrust Token', 'UTU': 'UTU Coin', 'UwU': 'UwU Lend', 'VADER': 'Vader', 'VAL': 'Sora Validator Token',
        'VBTC': 'Strudel BTC', 'VEGA': 'VEGA', 'VERSE': 'Verse', 'VIDYA': 'Vidya', 'VITE': 'Vite',
        'VOL': 'Volatility Protocol Token', 'VOW': 'Vow', 'VPP': 'Virtue Player Points', 'VRA': 'VERA', 'VRN': 'Varen',
        'VSP': 'VesperToken', 'VUSD': 'VUSD', 'VXV': 'VectorspaceAI', 'WARP': 'Warp Token', 'WAS': 'Wasder Token',
        'WASABI': 'Wasabi', 'WAVES': 'Waves', 'WAXE': 'WAX Economic Token', 'WBTC': 'Wrapped BTC', 'WCELO': 'Wrapped Celo',
        'WCUSD': 'Wrapped Celo Dollar', 'WETH': 'Wrapped Ether', 'WEVER': 'Wrapped Ever', 'WFIL': 'Wrapped Filecoin', 'WHALE': 'WHALE',
        'WISE': 'Wise Token', 'WIZARD': 'Forgotten Runes Wizards Cult', 'WKDA': 'Wrapped Kadena', 'wMEMO': 'Wrapped MEMO', 'WNCG': 'Wrapped NCG',
        'wNXM': 'Wrapped NXM', 'WOETH': 'Wrapped OETH', 'WOM': 'WOM Protocol', 'wOMI': 'Wrapped OMI Token', 'WOO': 'Wootrade Network',
        'WOOFY': 'Woofy', 'WOOL': 'WOOL', 'WOW': 'WOWswap', 'WOZX': 'EFFORCE IEO', 'wPE': 'OPES Finance',
        'WRLD': 'NFT Worlds', 'WSCRT': 'Wrapped SCRT', 'wstETH': 'Wrapped liquid staked Ether 2.0', 'WXMR': 'Wrapped XMR', 'WXRP': 'Wrapped XRP',
        'WZEC': 'Wrapped ZEC', 'X': 'X', 'X2Y2': 'X2Y2Token', 'XAI': 'SideShift Token', 'XBE': 'XBE',
        'XCAD': 'XCAD Token', 'xcRMRK': 'xcRMRK', 'XCUR': 'Curate', 'XDATA': 'Streamr (old)', 'XDB': 'digitalbits',
        'XDEFI': 'XDEFI', 'XED': 'Exeedme', 'XFIT': 'XFIT', 'XFT': 'Offshift', 'xFUND': 'unification.com/xfund',
        'XIO': 'XIO Network', 'XMON': 'XMON', 'XOR': 'Sora Token', 'XP': 'PolkaFantasy', 'XRT': 'Robonomics',
        'XRUNE': 'XRUNE Token', 'xSUSHI': 'SushiBar', 'XYO': 'XY Oracle', 'XYZ': 'XYZ Governance Token', 'YAM': 'YAM',
        'YAXIS': 'yAxis V2', 'YEL': 'YEL Token', 'YETI': 'Yearn Ecosystem Token Index', 'Yf-DAI': 'YfDAI.finance', 'YFI': 'yearn.finance',
        'YFII': 'YFII.finance', 'YGG': 'Yield Guild Games Token', 'YLA': 'Yearn Lazy Ape Index', 'YLD': 'Yield', 'YOP': 'YOP',
        'YPIE': 'Yearn Ecosystem Pie', 'yvBOOST': 'Yearn Compounding veCRV yVault', 'yveCRV-DAO': 'veCRV-DAO yVault', 
        'ZAP': 'ZAP TOKEN','ZCN': '0chain', 'ZEE': 'ZeroSwapToken', 'ZERO': 'Zero Money', 'ZETA': 'Zeta', 'ZKS': 'Zks',
        'zLOT': 'zLOT', 'ZRX': '0x Protocol Token', 'TCAP':'TCAP Token'},

    #polygon, 338 个币,3/2
    "polygon" :{'MATIC': 'MATIC', '$DG': 'decentral.games (PoS)', '1INCH': '1Inch (PoS)', 'AAVE': 'Aave (PoS)', 'ABI': 'Abachi', 
        'ACRE': 'Arable Protocol', 'ACX': 'Across Protocol Token (PoS)', 'ADDY': 'Adamant', 'ADS': 'Adshares (PoS)', 'agEUR': 'agEUR', 
        'ALGB': 'Algebra', 'ALPHA': 'PolyAlpha Finance', 'ANKR': 'Ankr (PoS)', 'ankrMATIC': 'Ankr Staked MATIC', 'APE': 'ApeCoin (PoS)',
        'ARPA': 'ARPA Token (PoS)', 'ASTRAFER': 'Astrafer', 'ATK': 'Attack', 'ATOM': 'Cosmos (PoS)', 'AUDIO': 'Audius', 
        'AURUM': 'RaiderAurum', 'AVAX': 'Avalanche Token', 'AX': 'AthleteX', 'axlUSDC': 'Axelar Wrapped USDC', 'AXMATIC': 'axMatic', 
        'AXN': 'Axion', 'AXS': 'Axie Infinity Shard (PoS)', 'BAL': 'Balancer (PoS)', 'BANANA': 'Banana', 'BANK': 'Bankless Token (PoS)',
        'BAT': 'Basic Attention Token (PoS)', 'BCT': 'Toucan Protocol: Base Carbon Tonne', 'BETS': 'BetSwirl Token', 
        'BICO': 'Biconomy Token', 'BIFI': 'beefy.finance', 'BLANK': 'GoBlank Token (PoS)', 'BLOK': 'BLOK', 'BNB': 'Binance Token', 
        'BNT': 'Bancor Network Token (PoS)', 'BOB': 'BOB', 'BOND': 'BarnBridge Governance Token (PoS)', 'BONE': 'Bone Token', 
        'BOOK': 'Bookie', 'BORING': 'BoringDAO (PoS)', 'BTC2x-FLI': 'BTC 2x Flexible Leverage Index (PoS)', 'BUSD': '(PoS) Binance USD',
        'BZRX': 'bZx Protocol Token (PoS)', 'C3': 'C3 Token', 'CEL': 'Celsius (PoS)', 'CERBY': 'Cerby Token', 
        'CGG': 'ChainGuardians Governance Token (PoS)', 'CHAIN': 'Chain Games', 'CHAMP': 'NFT Champions', 'CHECK': 'Check Token', 
        'CHUM': 'ChumHum', 'CIOTX': 'Crosschain IOTX', 'CNT': 'Cryption Network Token', 'CNTR': 'Centaur Token (PoS)', 
        'COLLAR': 'PolyPup Collar Token', 'COMBO': 'Furucombo (PoS)', 'COMP': '(PoS) Compound', 'COT': 'CosplayToken (PoS)', 
        'CREAM': 'Cream', 'CRV': 'CRV (PoS)', 'cSUSHI': 'cSUSHI', 'CVX': 'Convex Token (PoS)', 'DAFI': 'DAFI Token (PoS)', 
        'DAI': '(PoS) Dai Stablecoin', 'DATA': 'DATA Economy Index (PoS)', 'DEGEN': 'DEGEN Index (PoS)', 'DERC': 'DeRace Token', 
        'DERI': 'Deri Protocol', 'DFX': 'DFX Token (PoS)', 'DFYN': 'DFYN Token (PoS)', 'DG': 'Decentral Games (PoS)', 
        'DHT': 'dHedge DAO Token (PoS)', 'DINO': 'DinoSwap (PoS)', 'DMAGIC': 'Dark Magic', 'DOSE': 'DOSE', 
        'DPI': 'DefiPulse Index (PoS)', 'DRAX': 'Drax', 'DSLA': 'DSLA (PoS)', 'dTOP': 'dHEDGE Top Index (PoS)', 
        'DTX': 'DaTa eXchange Token (PoS)', 'DUCKIES': 'Yellow Duckies', 'DWEB': 'DecentraWeb (PoS)', 'DYDX': 'dYdX (PoS)', 
        'EGG': 'Waves Ducks', 'ELE': 'Eleven.finance', 'ELK': 'Elk', 'ELON': 'Dogelon (PoS)', 'EMON': 'EthermonToken', 
        'ENS': 'Ethereum Name Service (PoS)', 'EP': 'Elemental Particles', 'ERN': 'Ethernity Chain (PoS)', 
        'ETH2x-FLI': 'ETH 2x Flexible Leverage Index (PoS)', 'ETH2x-FLI-P': 'ETH 2x Flexible Leverage Index', 'ETHA': 'ETHA', 
        'EUROC': 'Euro Coin (PoS)', 'EUROe': 'EUROe Stablecoin', 'EURS': 'STASIS EURS Token (PoS)', 'FBX': 'FireBotToken', 
        'FEAR': 'Fear NFTs (PoS)', 'fireFBX': 'FireVault FBX', 'FISH': 'Fish', 'FLAME': 'FireStarter', 'FNC': 'Fancy Games', 
        'FODL': 'Fodl (PoS)', 'FOX': 'FOX (PoS)', 'FRAX': 'Frax (PoS)', 'FTM': 'Fantom Token', 
        'fxcbETH': 'Coinbase Wrapped Staked ETH (FXERC20)', 'FXS': 'Frax Share', 'FYN': 'Affyn', 'GAIA': 'GAIA Everworld', 
        'GAJ': 'PolyGaj Token', 'GAMER': 'GameStation', 'GENESIS': 'Genesis', 'GET': 'GET Protocol (PoS)', 'GFARM2': 'Gains V2', 
        'GHST': 'Aavegotchi GHST Token (PoS)', 'GIDDY': 'Giddy Token', 'GLM': 'Golem Network Token (PoS)', 'GLQ': 'GraphLinq (PoS)', 
        'GM': 'Guild Member Token', 'GMEE': 'GAMEE', 'GMS': 'Gemstones', 'GNO': 'Gnosis Token (PoS)', 'GNS': 'Gains Network', 
        'GNUS': 'Genius Token & NFT Collections', 'GOGO': 'GOGOcoin', 'gOHM': 'Governance OHM', 'GOVI': 'GOVI (PoS)', 
        'GRT': 'Graph Token (PoS)', 'GTC': 'Gitcoin (PoS)', 'GURU': 'Guru', 'GUSD': 'Gemini dollar (PoS)', 'GYSR': 'Geyser (PoS)', 
        'HEX': 'HEXX (PoS)', 'HOP': 'Hop', 'ibBTC': 'Interest-Bearing BTC', 'ICE': 'IceToken', 'IDLE': 'Idle (PoS)', 
        'IGG': 'IG Gold (PoS)', 'IMRTL': 'Immortl', 'INST': 'Instadapp (PoS)', 'INSUR': 'InsurAce (PoS)', 
        'IONX': 'Charged Particles - IONX (PoS)', 'IRON': 'IRON Stablecoin', 'IXT': 'PlanetIX', 'JPYC': 'JPY Coin (PoS)', 
        'JRT': 'Jarvis Reward Token (PoS)', 'KLIMA': 'Klima DAO', 'KNC': 'Kyber Network Crystal v2 (PoS)', 'KOM': 'Kommunitas', 
        'Krill': 'Krill', 'LCD': 'Lucidao', 'LDO': 'Lido DAO Token (PoS)', 'LICP': 'Liquid ICP', 'LINK': 'ChainLink Token', 
        'lsMATIC': 'Liquid Staked MATIC Index', 'MANA': '(PoS) Decentraland MANA', 'MASK': 'Mask Network (PoS)', 
        'MASQ': 'MASQ (PoS)', 'MaticX': 'Liquid Staking Matic (PoS)', 'MCHC': 'MCHCoin (PoS)', 'MCO2': 'Moss Carbon Credit (PoS)', 
        'Metis': 'Metis Token (PoS)', 'MFT': 'Hifi Finance', 'MHUNT': 'MetaShooter', 'MILK': 'Milk', 'MIM': 'Magic Internet Money', 
        'miMATIC': 'miMATIC', 'MITx': 'Morpheus Infrastructure Token (PoS)', 'MKR': 'MAKER (PoS)', 'MM': 'Million (PoS)', 
        'MOCA': 'Museum of Crypto Art', 'mOCEAN': 'Ocean Token (PoS)', 'MOD': 'MODEFI  (PoS)', 'MONA': 'Monavale', 
        'MOONED': 'MoonEdge', 'MSC': 'MetaSoccer Cash', 'mSHEESHA': 'SHEESHA POLYGON', 'MSU': 'MetaSoccer Universe', 
        'MTA': 'Meta (PoS)', 'MV': 'Metaverse (PoS)', 'MVI': 'Metaverse Index (PoS)', 'MYST': 'Mysterium (PoS)', 
        'NACHO': 'NACHO', 'NBO': 'Nature Based Offset', 'NCR': 'Neos Credits (PoS)', 'NCT': 'Toucan Protocol: Nature Carbon Tonne', 
        'NEXO': 'Nexo (PoS)', 'NFTE': 'NFTEarthOFT', 'NGNC': 'NGN Coin', 'NITRO': 'Nitro (PoS)', 'NPM': 'Neptune Mutual', 
        'NSDX': 'NASDEX Token', 'NSFW': 'Pleasure Coin', 'NSHARE': 'NSHARE', 'O3': 'O3 Swap Token', 'OM': 'MANTRA DAO (PoS)', 
        'OMEN': 'Augury Finance', 'OMNI': 'OmniCat', 'OOE': 'OpenOcean', 'OOKI': 'Ooki Token (PoS)', 'ORARE': 'One Rare Token', 
        'ORBS': 'Orbs (PoS)', 'PATH': 'PathDao (PoS)', 'PAUTO': 'Orbit Bridge Polygon AUTOv2', 'PAXG': 'Paxos Gold (PoS)', 
        'PBR': 'PolkaBridge', 'PECO': 'Polygon Ecosystem Index', 'PERL': 'Perlin (PoS)', 'PGOV': 'PGOV Token', 'pHBD': 'Polygon HBD', 
        'PICKLE': 'PickleToken (PoS)', 'PIXEL': 'Pixel', 'PKR': 'POLKER', 'PLA': 'PlayDapp Token (PoS)', 'PLOT': 'PlotX', 
        'POLAR': 'Polaris', 'polyBUNNY': 'Polygon BUNNY Token', 'POLYCUB': 'PolyCub', 'PolyDoge': 'PolyDoge', 
        'POOL': 'PoolTogether (PoS)', 'POP': 'Popcorn (PoS)', 'PROPEL': 'Propel', 'PROS': 'Prosper', 'PSP': 'ParaSwap (PoS)', 
        'pTREAT': 'pTREAT', 'PUSD': 'PUSD', 'PYD': 'PolyQuity Dollar', 'PYQ': 'PYQ', 'PYR': 'PYR Token', 'pZUG': 'pZUG', 
        'QI': 'Qi Dao', 'QUICK': 'Quickswap', 'RAI': 'Rai Reflex Index (PoS)', 'RAIDER': 'RaiderToken', 'RCN': 'RipioCreditNetwork', 
        'REIN': 'Reyna Ventures', 'renBTC': 'renBTC', 'renDGB': 'renDGB', 'renDOGE': 'renDOGE', 'renFIL': 'renFIL', 
        'REQ': 'Request', 'REVV': 'REVV', 'RIC': 'Ricochet', 'Ring': 'Darwinia (PoS)', 'RNDR': 'Render Token', 
        'ROLL': 'Polyroll Token', 'ROND': 'ROND Coin', 'ROUTE (PoS)': 'Route', 'ROY': 'Royale', 'RWD': 'Reward', 'SAND': 'SAND', 
        'SFI': 'Spice (PoS)', 'SFL': 'Sunflower Land', 'SHIB': 'SHIBA INU (PoS)', 'SNE': 'StrongNodeEdge Token', 'SNK': 'Snook', 
        'SNX': 'Synthetix Network Token (PoS)', 'SOL': 'SOL', 'SOS': 'SOS (PoS)', 'SPADE': 'PolygonFarm Finance', 
        'SPELL': 'Spell Token (PoS)', 'STG': 'StargateToken', 'stMATIC': 'Staked MATIC (PoS)', 'STND': 'Standard', 'STZ': '99Starz', 
        'SUPER': 'SuperFarm (PoS)', 'SUSHI': 'SushiToken (PoS)', 'SWAP': 'TrustSwap Token (PoS)', 'SX': 'SportX (PoS)', 
        'TCP': 'The Crypto Prophecies (PoS)', 'TECH': 'Cryptomeda', 'TEL': 'Telcoin (PoS)', 'TETU': 'TETU Reward Token', 
        'THREE': 'ThreeCoin', 'THX': 'THX Network (PoS)', 'TITAN': 'IRON Titanium Token', 'TNGBL': 'Tangible', 'TORN': 'Tornado Cash', 
        'TOWER': 'TOWER', 'TRACE': 'Trace Network', 'TRADE': 'Polytrade (PoS)', 'TRY': 'TryHards', 'TUSD': 'TrueUSD (PoS)', 
        'TUT': 'Tutellus token', 'UBI': 'Universal Basic Income (PoS)', 'UBO': 'Universal Basic Offset', 'UBT': 'Unibright (PoS)', 
        'UCO': 'UnirisToken (PoS)', 'UDT': 'Unlock Discount Token (PoS)', 'UFT': 'UniLend Finance Token (PoS)', 
        'UMA': 'UMA Voting Token v1 (PoS)', 'UND': 'Unbound Dollar', 'UNI': 'Uniswap (PoS)', 'UNITY': 'Unity', 
        'UNIX': 'UniX Gaming (PoS)', 'USD+': 'USD+', 'USDC': 'USD Coin', 'USDC.e': 'USD Coin (PoS)', 'USDT': '(PoS) Tether USD', 
        'USV': 'Universal Store of Value', 'VERSA': 'VersaGames', 'VISION': 'Vision Token (PoS)', 'VOXEL': 'VOXEL Token', 
        'VSP': 'VesperToken (PoS)', 'VSQ': 'VSQ', 'WARU': 'Waru Token V2', 'wBAN': 'Wrapped Banano', 'WBTC': '(PoS) Wrapped BTC', 
        'wCCX': 'WrappedConceal', 'WETH': 'Wrapped Ether', 'WFIL': 'Wrapped Filecoin (PoS)', 'WISE': 'Wise Token (PoS)', 
        'WLD': 'wLitiDAO', 'WMATIC': 'Wrapped Matic', 'WOLF': 'moonwolf.io', 'WOMBAT': 'Wombat', 'WOO': 'Wootrade Network (PoS)', 
        'WOOFY': 'Woofy', 'WORK': 'The Employment Commons Work Token (PoS)', 'WOW': 'WOWswap', 'WRX': 'Wazirx (PoS)', 
        'WSG': 'Wall Street Games', 'WSPP': 'WolfSafePoorPeople', 'XCAD': 'XCAD Token (PoS)', 
        'xDG': 'Decentral Games Governance (PoS)', 'XED': 'Exeedme (PoS)', 'XGEM': 'Exchange Genesis Ethlas Medium', 
        'xSUSHI': 'SushiBar (PoS)', 'YFI': 'yearn.finance', 'YLD': 'Yield (PoS)', 'ZED': 'ZED RUN', 'ZRX': '0x Protocol Token (PoS)'},
    
    
    # BNB, 262 个币,3/2
    "bnb":{'BNB': 'BNB Chain Native Token', '8PAY': '8PAY Network', 'ADA': 'Cardano Token', 'ADX': 'AdEx Network', 'agEUR': 'agEUR', 
        'ALICE': 'ALICE', 'ALPACA': 'AlpacaToken', 'ALPHA': 'AlphaToken', 'ANKR': 'Ankr', 'anyMTLX': 'MTLX-ERC20', 
        'anySUSHI': 'SushiToken', 'AOG': 'AgeOfGods', 'APE': 'ApeCoin', 'APX': 'ApolloX Token', 'APYS': 'APYSwap', 'ARV': 'ARIVA', 
        'ASR': 'AS Roma', 'ATA': 'Automata', 'ATM': 'Atletico de Madrid', 'ATOM': 'Cosmos Token', 'AUTO': 'AUTOv2', 
        'axlUSDC': 'Axelar Wrapped USDC', 'AXS': 'Axie Infinity Shard', 'BAKE': 'BakeryToken', 'bALBT': 'AllianceBlock', 
        'BAND': 'Band Protocol Token', 'BAT': 'Basic Attention Token', 'BATH': 'Battle Hero Coin', 'BBT': 'BitBook', 
        'bCFX': 'BSC Conflux', 'BCH': 'Bitcoin Cash Token', 'BCOIN': 'Bomber Coin', 'BDO': 'bDollar', 'BELT': 'BELT Token', 
        'BETA': 'Beta Token', 'BETH': 'Binance Beacon ETH', 'BIFI': 'beefy.finance', 'BLK': 'BLINk', 'BOB': 'BOB', 'BONDLY': 'Bondly', 
        'BORING': 'BoringDAO', 'BP': 'BunnyPark', 'bROOBEE': 'ROOBEE', 'BRY': 'Berry Tributes', 'BSCPAD': 'BSCPAD.com', 'BSCX': 'BSCX', 
        'BSW': 'Biswap', 'BTCB': 'BTCB Token', 'BTCST': 'StandardBTCHashrateToken', 'BTR': 'Bitrue Token', 'BTT': 'BitTorrent', 
        'BUNNY': 'Bunny Token', 'BURGER': 'Burger Swap', 'BUSD': 'BUSD Token', 'C98': 'Coin98', 'Cake': 'PancakeSwap Token', 
        'CAN': 'CanYaCoin', 'CDT': 'CheckDot', 'CEEK': 'CEEK', 'CERBY': 'Cerby Token', 'CGG': 'pTokens CGG', 'CHESS': 'Chess', 
        'CHR': 'Chroma', 'CO': 'CO', 'COMP': 'Compound Coin', 'CREAM': 'Cream', 'CTK': 'CertiK Token', 'CYC': 'Cyclone Protocol', 
        'DAI': 'Dai Token', 'DAR': 'Dalarnia', 'DERI': 'Deri', 'DEXE': 'DeXe', 'DICE': 'Dice.finance Token', 'DITTO': 'Ditto', 
        'DODO': 'DODO bird', 'DOGE': 'Dogecoin', 'DOT': 'Polkadot Token', 'DUSK': 'Dusk Network', 'DVI': 'Dvision', 'EGLD': 'Elrond', 
        'EKTA v2': 'EKTA v2', 'EOS': 'EOS Token', 'EPS': 'Ellipsis', 'ERA': 'Era Token', 'ERTHA': 'ERTHA Token', 
        'ETERNAL': 'CryptoMines Eternal', 'ETH': 'Ethereum Token', 'FIL': 'Filecoin', 'FINE': 'Refinable', 'FOR': 'The Force Token', 
        'FORM': 'Formation Finance', 'FRAX': 'Frax', 'FRIES': 'fry.world', 'FRONT': 'Frontier Token', 'Froyo': 'Froyo', 
        'FUEL': 'Fuel', 'FUSE': 'Fuse Token on BSC', 'FXS': 'Frax Share', 'GAL': 'Project Galaxy', 'GMEE': 'GAMEE', 
        'GMT': 'Green Metaverse Token', 'GQ': 'Galactic Quadrant', 'HAI': 'Hacken Token', 'HAPPY': 'HappyFans', 'HARD': 'HARD', 
        'HAY': 'Hay Stablecoin', 'Helmet': 'Helmet.insure Governance Token', 'HERO': 'Metahero', 'HFT': 'Hashflow', 
        'HIGH': 'Highstreet Token', 'HOOK': 'Hook Token', 'HOTCROSS': 'Hot Cross Token', 'HZN': 'Horizon Protocol', 'ICE': 'IceToken', 
        'IDIA': 'Impossible Decentralized Incubator Access Token', 'INJ': 'Injective Protocol', 'IOTX': 'IoTeX Network', 
        'JASMY': 'JasmyCoin', 'JGN': 'Juggernaut DeFi', 'JNTR/b': 'JNTR/b', 'JUV': 'Juventus', 'KALM': 'Kalmar Token', 'KAVA': 'KAVA', 
        'KRS': 'Kingdom Raids', 'KUN': 'QIAN governance token', 'LAZIO': 'FC Lazio Fan Token', 'LIEN': 'lien on xDai from xDai', 
        'LINA': 'Linear Token', 'LINK': 'ChainLink Token', 'LIT': 'Litentry', 'LNR': 'Lunar', 'LOA': 'League Of Ancients', 
        'LTC': 'Litecoin Token', 'LTO': 'LTO Network', 'lUSD': 'lUSD', 'MAI': 'Mai Stablecoin', 'mAMZN': 'Mirror AMZN Token', 
        'MANA': 'Decentraland', 'MARSH': 'UnmarshalToken', 'MASK': 'Mask Network', 'MATH': 'MATH Token', 'MBOX': 'Mobox', 
        'MCB': 'MCDEX Token', 'MCRN': 'MacaronSwap Token', 'Metis': 'Metis Token', 'mGOOGL': 'Mirror GOOGL Token', 
        'MGP': 'Magpie Token', 'MHUNT': 'MetaShooter', 'MIM': 'Magic Internet Money', 'MIX': 'MixMarvel Token', 'MM': 'Million', 
        'mNFLX': 'Mirror NFLX Token', 'MTRG': 'Wrapped MTRG on BSC by Meter.io', 'mTSLA': 'Mirror TSLA Token', 'NABOX': 'Nabox Token', 
        'NAR': 'NAR Token', 'NBT': 'NanoByte Token', 'NFTE': 'NFTEarthOFT', 'nICE': 'NICE', 'NPM': 'Neptune Mutual', 'NULS': 'Nuls', 
        'NUM': 'NUM Token [via ChainPort.io]', 'NVT': 'NerveNetwork', 'NYA': 'Nyanswop Token', 'O3': 'O3 Swap Token', 'OG': 'OG', 
        'OLE': 'OpenLeverage', 'OMNI': 'OmniCat', 'ONE': 'Harmony ONE', 'ONT': 'Ontology Token', 'ORBS': 'Orbs', 'pCWS': 'PolyCrowns', 
        'PEAK': 'PEAKDEFI', 'PEEL': 'Meta Apes Peel', 'PERL': 'Perlin', 'PEX': 'PEAR DAO', 'PHA': 'Phala Network', 'PMON': 'Polkamon', 
        'PORTO': 'FC Porto Fan Token', 'POTS': 'Moonpot', 'PROM': 'Prometeus', 'PROS': 'Prosper', 'PSG': 'Paris Saint-Germain', 
        'QBT': 'Qubit Token', 'QI': 'BENQI', 'QUIDD': 'QUIDD', 'QUSD': 'QUSD Stablecoin', 'RACA': 'Radio Caca V2', 
        'RAMP': 'RAMP DEFI', 'RDNT': 'Radiant', 'REEF': 'Reef.finance', 'REVV': 'REVV', 'RFOX': 'RFOX', 'RPG': 'Rangers Protocol Gas', 
        'SAND': 'The Sandbox', 'SANTOS': 'FC Santos Fan Token', 'SDAO': 'Singularity Dao', 'SFP': 'SafePal Token', 
        'SFUND': 'SeedifyFund', 'SHEESHA': 'Sheesha Finance', 'SHWA': 'ShibaWallet', 'SKILL': 'CryptoBlades Skill Token', 
        'SPARTA': 'SPARTAN PROTOCOL TOKEN', 'SPELL': 'Spell Token', 'SPIN': 'Spintop', 'SPS': 'Splintershards', 
        'sSPELL': 'Staked Spell Tokens', 'STAX': 'StableXSwap', 'STG': 'StargateToken', 'STM': 'Streamity', 'SUSHI': 'SushiToken', 
        'SXP': 'Swipe', 'TEN': 'Tenet', 'THG': 'Thetan Gem', 'TINC': 'Tiny Coin', 'TKO': 'Tokocrypto Token', 
        'TLM': 'Alien Worlds Trilium', 'TLOS': 'pTokens TLOS', 'TPT': 'TokenPocket Token', 'TRIVIA': 'Trivian Token', 'TRX': 'TRON', 
        'TT': 'BSC-Peg Thunder Token', 'TUSD': 'TrueUSD', 'TWT': 'Trust Wallet', 'TXL': 'Tixl Token', 'UNFI': 'UNFI', 'UNI': 'Uniswap', 
        'USDC': 'USD Coin', 'USDT': 'Tether USD', 'USDV': 'USDV', 'USDX': 'USDX', 'UST': 'Wrapped UST Token', 'VAI': 'VAI Stablecoin', 
        'VET': 'VeChain', 'VRT': 'Venus Reward Token', 'WATCH': 'yieldwatch', 'WBNB': 'Wrapped BNB', 'wCCX': 'Wrapped Conceal (wCCX)', 
        'WENLAMBO': 'WenLambo', 'WIN': 'WINk', 'WMX': 'Wombex Token', 'WOM': 'Wombat Token', 'WOO': 'Wootrade Network', 
        'WOOP': 'Woonkly Power', 'WOW': 'WOWSwap', 'WSG': 'Wall Street Games', 'wSOTE': 'Soteria', 
        'XCAD': 'Chainport.io-Peg XCAD Token', 'XCV': 'XCarnival', 'XED': 'Exeedme', 'XMS': 'Mars Ecosystem Token', 
        'XRP': 'XRP Token', 'XTZ': 'Tezos Token', 'XVS': 'Venus', 'XWG': 'XWG', 'YEL': 'YEL Token', 'YFI': 'yearn.finance', 
        'YFII': 'YFII.finance Token', 'ZEC': 'Zcash Token', 'ZETA': 'Zeta', 'ZIL': 'Zilliqa', 'Zoo': 'ZooToken'},

    # arbitrum_one, 150 个币,3/2
    "arbitrum_one":{'ETH': 'Ether', '$SHARBI': 'SHARBI', 'AAVE': 'Aave Token', 'ACX': 'Across Protocol Token', 'ADoge': 'ArbiDoge', 
        'aEGGS': 'Arbitrum Eggs', 'agEUR': 'agEUR', 'AGS': 'Gambler Shiba', 'ALCH': 'Alchemy', 'aMoon': 'ArbiMoon', 'ANIMA': 'Anima', 
        'ANKAA': 'AnkaaToken', 'ARB': 'Arbitrum', 'ArbiFLUX': 'ArbiFLUX', 'ARBIS': 'ARBIS | We have the yields', 
        'ARBY': 'Adamant Token (Arbitrum)', 'ARBYS': 'Arbys', 'ARVAULT': 'ArVault', 'axlTIA': 'Axelar Wrapped TIA', 
        'axlUSDC': 'Axelar Wrapped USDC', 'BADGER': 'Badger', 'BAL': 'Balancer', 'BARB': 'Baby Arbitrum', 'BELA': 'Beluga Token', 
        'BIFI': 'beefy.finance', 'BUCK': 'Arbucks', 'CAP': 'Cap', 'cbETH': 'Coinbase Wrapped Staked ETH', 'CELR': 'CelerToken', 
        'COMP': 'Compound', 'CREAM': 'Cream', 'CREDA': 'CreDA Protocol Token', 'CRV': 'Curve DAO Token', 
        'CVOL': 'Crypto Volatility Token', 'DAI': 'Dai Stablecoin', 'DICE': 'Party Dice', 'DODO': 'DODO bird', 'DOG': 'The Doge NFT', 
        'DPX': 'Dopex Governance Token', 'DUSD': 'DigitalDollar', 'DVF': 'DeversiFi Token', 'DXD': 'DXdao', 'EMAX': 'EthereumMax', 
        'EUROe': 'EUROe Stablecoin', 'EUX': 'dForce EUR', 'EXPO': 'Exponential Capital', 'FLUID': 'FluidFi', 'FLUX': 'Flux Protocol', 
        'FRAX': 'Frax', 'FRM': 'Ferrum Network Token', 'fUSDC': 'Fluid USDC', 'FUSE': 'Fuse Token', 'FXS': 'Frax Share', 
        'GBOT': 'GBOT', 'GMX': 'GMX', 'GNO': 'Gnosis Token', 'gOHM': 'Governance OHM', 'GOVI': 'GOVI', 'GRT': 'Graph Token', 
        'GTA': 'GTA', 'HAMI': 'Hamachi', 'HASH': 'HashDAO Token', 'HND': 'Hundred Finance', 'HWT': 'HonorWorld Token', 
        'ICE': 'Ice Token', 'IMO': 'Ideamarket', 'IMX': 'Impermax', 'jDPX': 'Jones DPX', 'jETH': 'Jones ETH', 'jgOHM': 'Jones gOHM', 
        'JONES': 'Jones DAO', 'jrDPX': 'Jones rDPX', 'LINK': 'ChainLink Token', 'LIQD': 'Liquid', 'LON': 'Tokenlon', 
        'LPT': 'Livepeer Token', 'lqETH': 'liquid ETH', 'LRC': 'LoopringCoin V2', 'LUSD': 'LUSD Stablecoin', 'MAGIC': 'MAGIC', 
        'MAGNET': 'Magnethereum', 'MAI': 'Mai Stablecoin', 'MATH': 'MATH Token', 'MCB': 'MCDEX Token', 'MIM': 'Magic Internet Money', 
        'MMT': 'MyMetaTrader Token', 'NFTE': 'NFTEarthOFT', 'NIFLOKI': 'Nitro Floki', 'NISHIB': 'NitroShiba', 'NOLA': 'Nola', 
        'NPM': 'Neptune Mutual', 'NUON': 'NUON', 'NYAN': 'ArbiNYAN', 'O3': 'O3 Swap Token', 'OLE': 'OpenLeverage', 'OMNI': 'OmniCat', 
        'pAAPL': 'Poison.Finance Apple Potion', 'pAMZN': 'Poison.Finance Amazon Potion', 'PANA': 'Pana DAO', 'PEPE': 'Pepe', 
        'pGOLD': 'Poison.Finance Gold Potion', 'PGS': 'PegasusBot', 'PL2': 'Plenny', 'PLS': 'Plutus', 'plsDPX': 'Plutus DPX', 
        'plsJONES': 'Plutus JONES', 'pOIL': 'Poison.Finance Oil Potion', 'PPEGG': 'Parrot Egg', 'PREMIA': 'Premia', 
        'pSLVR': 'Poison.Finance Silver Potion', 'pTSLA': 'Poison.Finance Tesla Potion', 'RDNT': 'Radiant', 
        'RDNT(OLD)': 'Radiant(OLD)', 'RDPX': 'Dopex Rebate Token', 'rETH': 'Rocket Pool ETH', 'RGT': 'Rari Governance Token', 
        'ROSX': 'Roseon', 'SDT': 'Stake DAO Token', 'Silo': 'Silo Governance Token', 'SIS': 'Symbiosis', 
        'slUSDT': 'Shared-liquidity USDT', 'SPELL': 'Spell Token', 'sSPELL': 'Staked Spell Tokens', 'STG': 'StargateToken', 
        'STRP': 'Strips Token', 'sUSD': 'Synth sUSD', 'SUSHI': 'SushiToken', 'SVY': 'Savvy', 'SWPR': 'Swapr', 'TCR': 'Tracer', 
        'TURBO': 'Turbo', 'TUSD': 'TrueUSD', 'UMAMI': 'Umami', 'UNI': 'Uniswap', 'USDC': 'USD Coin (Native)', 
        'USDC.e': 'Bridged USDC (Arb1)', 'USDT': 'Tether USD', 'USDV': 'USDV', 'USX': 'dForce USD', 'VELA': 'Vela Exchange', 
        'VISR': 'VISOR', 'W3N': 'Web3 No Value', 'WBTC': 'Wrapped BTC', 'WETH': 'Wrapped Ether', 'WOO': 'Wootrade Network', 
        'wsOHM': 'Wrapped sOHM', 'YDF': 'Yieldification', 'YFI': 'yearn.finance', 'Z2O': 'ZeroTwOhm', 'ZTX': 'ZTX'},

    "base":{'ETH': 'Ether', 'AXL': 'Axelar', 'axlDAI': 'Axelar Wrapped DAI', 'axlUSDC': 'Axelar Wrapped USDC', 'AYB': 'All Your Base', 
        'BAL': 'Balancer', 'BALD': 'Bald', 'BOGE': 'Boge', 'BOT': 'BASE BOT', 'cbETH': 'Coinbase Wrapped Staked ETH', 
        'COMP': 'Compound', 'DAI': 'Dai Stablecoin', 'FARM': 'FARM Reward Token', 'Fren Pet': 'Fren Pet', 'HAN': 'HanChain', 
        'HANeP': 'HANePlatform', 'iFARM': 'iFARM', 'KRAV': 'KRAV', 'MBS': 'MBS', 'MOCHI': 'Mochi (old)', 
        'MOCHITOSHI': 'Mochi and Toshi', 'NFTE': 'NFTEarthOFT', 'NPC': 'Non-Playable Coin', 'OMNI': 'OmniCat', 'SEAM': 'Seamless', 
        'SMUDCAT': 'Smudge Cat', 'SUSHI': 'SushiToken', 'TOSHI': 'Toshi (old)', 'TYBG': 'Base God', 'USDbC': 'USD Base Coin', 
        'USDC': 'USD Coin', 'VELA': 'Vela Token', 'WETH': 'Wrapped Ether', 'XEN': 'Xena', 'YOU': 'Youcoin', 'ZRX': '0x Protocol Token'
    }
}


