
# 注意，这个currency有些币没有在上面显示 ，却能生成的。主要是  ETH，WETH,BTC,WBTC,renBTC,sBTC 可再做一次对主流币种的再次检测 
uniswap_currencies = {
    # 250个，其中'ETH':'ETH’ 没有记录    2/28
    "ethereum" : {'ETH':'ETH',  '1INCH': '1inch', 'AAVE': 'Aave', 'ABT': 'Arcblock', 'ACH': 'Alchemy Pay', 'ADX': 'Ambire AdEx' ,
        'AERGO': 'Aergo', 'agEUR': 'agEur', 'AGLD': 'Adventure Gold', 'AIOZ': 'AIOZ Network', 'ALCX': 'Alchemix' ,'STRK':'Starknet',
        'ALEPH': 'Aleph im', 'ALI': 'Alethea Artificial Liquid Intelligence', 'ALICE': 'My Neighbor Alice', 'ALPHA': 'Alpha Venture DAO', 'AMP': 'Amp' ,
        'ANKR': 'Ankr', 'ANT': 'Aragon', 'APE': 'ApeCoin', 'API3': 'API3', 'ARB': 'Arbitrum' ,
        'ARPA': 'ARPA Chain', 'ASH': 'ASH', 'ASM': 'Assemble Protocol', 'AST': 'AirSwap', 'ATA': 'Automata' ,
        'AUCTION': 'Bounce', 'AUDIO': 'Audius', 'AVT': 'Artverse Token', 'AXL': 'Axelar', 'AXS': 'Axie Infinity' ,
        'BADGER': 'Badger DAO', 'BAL': 'Balancer', 'BAND': 'Band Protocol', 'BAT': 'Basic Attention Token', 'BICO': 'Biconomy' ,
        'BIGTIME': 'Big Time', 'BIT': 'BitDAO', 'BLUR': 'Blur', 'BLZ': 'Bluzelle', 'BNT': 'Bancor Network Token' ,
        'BOBA': 'Boba Network', 'BOND': 'BarnBridge', 'BTRST': 'Braintrust', 'BUSD': 'Binance USD', 'C98': 'Coin98' ,
        'cbETH': 'Coinbase Wrapped Staked ETH', 'CELO': 'Celo native asset (Wormhole)', 'CELR': 'Celer Network', 'CHR': 'Chromia', 'CHZ': 'Chiliz' ,    
        'CLV': 'Clover Finance', 'COMP': 'Compound', 'COTI': 'COTI', 'COVAL': 'Circuits of Value', 'CQT': 'Covalent' ,
        'CRO': 'Cronos', 'CRPT': 'Crypterium', 'CRV': 'Curve DAO Token', 'CTSI': 'Cartesi', 'CTX': 'Cryptex Finance' ,
        'CUBE': 'Somnium Space CUBEs', 'CVC': 'Civic', 'CVX': 'Convex Finance', 'DAI': 'Dai Stablecoin', 'DAR': 'Mines of Dalarnia' ,
        'DDX': 'DerivaDAO', 'DENT': 'Dent', 'DEXT': 'DexTools', 'DIA': 'DIA', 'DNT': 'district0x' ,
        'DPI': 'DeFi Pulse Index', 'DREP': 'Drep', 'DYDX': 'dYdX', 'DYP': 'DeFi Yield Protocol', 'ELA': 'Elastos' ,
        'ELON': 'Dogelon Mars', 'ENJ': 'Enjin Coin', 'ENS': 'Ethereum Name Service', 'ERN': 'Ethernity Chain', 'EUL': 'Euler' ,
        'EUROC': 'Euro Coin', 'FARM': 'Harvest Finance', 'FET': 'Fetch ai', 'FIS': 'Stafi', 'FORT': 'Forta' ,
        'FORTH': 'Ampleforth Governance Token', 'FOX': 'ShapeShift FOX Token', 'FRAX': 'Frax', 'FTM': 'Fantom', 'FX': 'Function X' ,
        'FXS': 'Frax Share', 'GAL': 'Project Galaxy', 'GALA': 'GALA', 'GFI': 'Goldfinch', 'GHST': 'Aavegotchi' ,
        'GLM': 'Golem', 'GNO': 'Gnosis Token', 'GODS': 'Gods Unchained', 'GRT': 'The Graph', 'GTC': 'Gitcoin' ,
        'GUSD': 'Gemini Dollar', 'GYEN': 'GYEN', 'HFT': 'Hashflow', 'HIGH': 'Highstreet', 'HOPR': 'HOPR' ,
        'IDEX': 'IDEX', 'ILV': 'Illuvium', 'IMX': 'Immutable X', 'INDEX': 'Index Cooperative', 'INJ': 'Injective' ,
        'INV': 'Inverse Finance', 'IOTX': 'IoTeX', 'JAM': 'Geojam', 'JASMY': 'JasmyCoin', 'JUP': 'Jupiter' ,
        'KEEP': 'Keep Network', 'KEY': 'SelfKey', 'KNC': 'Kyber Network Crystal', 'KP3R': 'Keep3rV1', 'KRL': 'KRYLL' ,
        'LCX': 'LCX', 'LDO': 'Lido DAO', 'LINK': 'ChainLink Token', 'LOKA': 'League of Kingdoms', 'LOOM': 'Loom Network' ,
        'LPT': 'Livepeer', 'LQTY': 'Liquity', 'LRC': 'LoopringCoin V2', 'LUSD': 'Liquity USD', 'MANA': 'Decentraland' ,
        'MASK': 'Mask Network', 'MATH': 'MATH', 'MATIC': 'Polygon', 'MC': 'Merit Circle', 'MCO2': 'Moss Carbon Credit' ,
        'MDT': 'Measurable Data Token', 'METIS': 'Metis', 'MIM': 'Magic Internet Money', 'MIR': 'Mirror Protocol', 'MKR': 'Maker' ,
        'MLN': 'Melon', 'MONA': 'Monavale', 'MPL': 'Maple', 'MTL': 'Metal', 'MULTI': 'Multichain' ,
        'MUSD': 'mStable USD', 'MUSE': 'Muse DAO', 'MV': 'GensoKishi Metaverse', 'MXC': 'MXC', 'NCT': 'PolySwarm' ,
        'NEST': 'Nest Protocol', 'NKN': 'NKN', 'NMR': 'Numeraire', 'NU': 'NuCypher', 'OCEAN': 'Ocean Protocol' ,
        'OGN': 'Origin Protocol', 'OMG': 'OMG Network', 'ONDO': 'Ondo Finance', 'ORCA': 'ORCA Alliance', 'ORN': 'Orion Protocol' ,
        'OXT': 'Orchid', 'PAX': 'PayperEx', 'PAXG': 'PAX Gold', 'PEPE': 'Pepe', 'PERP': 'Perpetual Protocol' ,
        'PLA': 'PlayDapp', 'PLU': 'Pluton', 'POLS': 'Polkastarter', 'POLY': 'Polymath', 'POND': 'Marlin' ,
        'POWR': 'Power Ledger', 'PRIME': 'Prime', 'PRO': 'Propy', 'PRQ': 'PARSIQ', 'PSTAKE': 'pSTAKE Finance' ,
        'PYUSD': 'PayPal USD', 'QNT': 'Quant', 'QRDO': 'Qredo', 'QSP': 'Quantstamp', 'QUICK': 'Quickswap' ,
        'RAD': 'Radicle', 'RAI': 'Rai Reflex Index', 'RARE': 'SuperRare', 'RARI': 'Rarible', 'RBC': 'Rubic' ,
        'RBN': 'Ribbon Finance', 'REN': 'Republic Token', 'REP': 'Reputation Augur v1', 'REPv2': 'Reputation Augur v2', 'REQ': 'Request' ,
        'REVV': 'REVV', 'RGT': 'Rari Governance Token', 'RLC': 'iExec RLC', 'RLY': 'Rally', 'RNDR': 'Render Token' ,
        'ROOK': 'Rook', 'SAND': 'The Sandbox', 'SHIB': 'Shiba Inu', 'SHPING': 'Shping', 'SKL': 'SKALE' ,
        'SLP': 'Smooth Love Potion', 'SNT': 'Status', 'SNX': 'Synthetix Network Token', 'SOCKS': 'Unisocks', 'SOL': 'SOL Wormhole' ,
        'SPELL': 'Spell Token', 'STG': 'Stargate Finance', 'STORJ': 'Storj Token', 'STX': 'Stox', 'SUKU': 'SUKU' ,
        'SUPER': 'SuperFarm', 'sUSD': 'Synth sUSD', 'SUSHI': 'Sushi', 'SWFTC': 'SWFTCOIN', 'SXP': 'Swipe' ,
        'SYLO': 'Sylo', 'SYN': 'Synapse', 'T': 'Threshold Network', 'tBTC': 'tBTC', 'TIME': 'ChronoTech' ,
        'TLM': 'Alien Worlds', 'TOKE': 'Tokemak', 'TONE': 'TE FOOD', 'TRAC': 'OriginTrail', 'TRB': 'Tellor' ,
        'TRIBE': 'Tribe', 'TRU': 'TrueFi', 'TVK': 'The Virtua Kolect', 'UMA': 'UMA Voting Token v1', 'UNFI': 'Unifi Protocol DAO' ,
        'UNI': 'Uniswap', 'UPI': 'Pawtocol', 'USDC': 'USDCoin', 'USDT': 'Tether USD', 'VGX': 'Voyager Token' ,
        'WAMPL': 'Wrapped Ampleforth', 'WBTC': 'Wrapped BTC', 'WCFG': 'Wrapped Centrifuge', 'WETH': 'Wrapped Ether', 'WOO': 'WOO Network' ,
        'XCN': 'Chain', 'XSGD': 'XSGD', 'XYO': 'XYO Network', 'YFI': 'yearn finance', 'YFII': 'DFI money' ,
        'YGG': 'Yield Guild Games', 'Zeta': 'Zetachain', 'ZRX': '0x Protocol Token' ,},

    # 142 个代币，2/28号
    "arbitrum" : {'ETH':'ETH','1INCH': '1inch', 'AAVE': 'Aave', 'agEUR': 'agEur', 'AGLD': 'Adventure Gold', 'AIOZ': 'AIOZ Network', 
        'ALEPH': 'Aleph im', 'ALI': 'Alethea Artificial Liquid Intelligence', 'ALPHA': 'Alpha Venture DAO', 'ANKR': 'Ankr', 
        'APE': 'ApeCoin', 'API3': 'API3', 'ARB': 'Arbitrum', 'ATA': 'Automata', 'AXL': 'Axelar', 'AXS': 'Axie Infinity', 
        'BADGER': 'Badger DAO', 'BAL': 'Balancer', 'BAT': 'Basic Attention Token', 'BICO': 'Biconomy', 'BIT': 'BitDAO', 
        'BLUR': 'Blur', 'BNT': 'Bancor Network Token', 'BOND': 'BarnBridge', 'BUSD': 'Binance USD', 
        'cbETH': 'Coinbase Wrapped Staked ETH', 'CELO': 'Celo native asset (Wormhole)', 'CELR': 'Celer Network', 'COMP': 'Compound', 
        'COTI': 'COTI', 'CRO': 'Cronos', 'CRV': 'Curve DAO Token', 'CTSI': 'Cartesi', 'CTX': 'Cryptex Finance', 'CVC': 'Civic', 
        'CVX': 'Convex Finance', 'DAI': 'Dai Stablecoin', 'DEXT': 'DexTools', 'DIA': 'DIA', 'DNT': 'district0x', 
        'DPI': 'DeFi Pulse Index', 'DYDX': 'dYdX', 'ELON': 'Dogelon Mars', 'ENJ': 'Enjin Coin', 'ENS': 'Ethereum Name Service', 
        'ERN': 'Ethernity Chain', 'EUROC': 'Euro Coin', 'FARM': 'Harvest Finance', 'FET': 'Fetch ai', 'FIS': 'Stafi', 'FORT': 'Forta', 
        'FOX': 'ShapeShift FOX Token', 'FRAX': 'Frax', 'FTM': 'Fantom', 'FXS': 'Frax Share', 'GAL': 'Project Galaxy', 'GALA': 'GALA', 
        'GMX': 'GMX', 'GNO': 'Gnosis Token', 'GRT': 'The Graph', 'GTC': 'Gitcoin', 'GYEN': 'GYEN', 'HIGH': 'Highstreet', 
        'HOPR': 'HOPR', 'ILV': 'Illuvium', 'IMX': 'Immutable X', 'INJ': 'Injective', 'JASMY': 'JasmyCoin', 'LDO': 'Lido DAO', 
        'LINK': 'ChainLink Token', 'LPT': 'Livepeer', 'LQTY': 'Liquity', 'LRC': 'LoopringCoin V2', 'LUSD': 'Liquity USD', 
        'MAGIC': 'MAGIC', 'MANA': 'Decentraland', 'MASK': 'Mask Network', 'MATH': 'MATH', 'MATIC': 'Polygon', 'METIS': 'Metis', 
        'MIM': 'Magic Internet Money', 'MKR': 'Maker', 'MLN': 'Melon', 'MPL': 'Maple', 'MULTI': 'Multichain', 'MXC': 'MXC', 
        'NCT': 'PolySwarm', 'NKN': 'NKN', 'NMR': 'Numeraire', 'OCEAN': 'Ocean Protocol', 'OGN': 'Origin Protocol', 
        'OMG': 'OMG Network', 'ORN': 'Orion Protocol', 'PAXG': 'PAX Gold', 'PEPE': 'Pepe', 'PERP': 'Perpetual Protocol', 
        'POLS': 'Polkastarter', 'POLY': 'Polymath', 'POND': 'Marlin', 'POWR': 'Power Ledger', 'PRIME': 'Prime', 'PRQ': 'PARSIQ', 
        'QNT': 'Quant', 'RAI': 'Rai Reflex Index', 'RARI': 'Rarible', 'RBC': 'Rubic', 'REN': 'Republic Token', 'REQ': 'Request', 
        'RGT': 'Rari Governance Token', 'RLC': 'iExec RLC', 'RNDR': 'Render Token', 'SAND': 'The Sandbox', 'SHIB': 'Shiba Inu', 
        'SKL': 'SKALE', 'SNT': 'Status', 'SNX': 'Synthetix Network Token', 'SOCKS': 'Unisocks', 'SOL': 'SOL Wormhole ', 
        'SPELL': 'Spell Token', 'STG': 'Stargate Finance', 'STORJ': 'Storj Token', 'SUPER': 'SuperFarm', 'sUSD': 'Synth sUSD', 
        'SUSHI': 'Sushi', 'SYN': 'Synapse', 'T': 'Threshold Network', 'tBTC': 'tBTC', 'TRB': 'Tellor', 'TRIBE': 'Tribe', 
        'UMA': 'UMA Voting Token v1', 'UNI': 'Uniswap', 'USDC': 'USDCoin', 'USDC.e': 'Bridged USDC', 'USDT': 'Tether USD', 
        'WAMPL': 'Wrapped Ampleforth', 'WBTC': 'Wrapped BTC', 'WETH': 'Wrapped Ether', 'WOO': 'WOO Network', 'XCN': 'Chain', 
        'XSGD': 'XSGD', 'YFI': 'yearn finance', 'Zeta': 'Zetachain', 'ZRX': '0x Protocol Token'},
    
    # 只有 51个 2/28，2/28号
    "optimism":{'ETH':'ETH','1INCH': '1inch', 'AAVE': 'Aave', 'ARPA': 'ARPA Chain', 'BAL': 'Balancer', 'BOND': 'BarnBridge',
        'BTRST': 'Braintrust', 'BUSD': 'Binance USD', 'cbETH': 'Coinbase Wrapped Staked ETH', 'CELO': 'Celo native asset (Wormhole)', 
        'CRV': 'Curve DAO Token', 'CTSI': 'Cartesi', 'DAI': 'Dai Stablecoin', 'ENS': 'Ethereum Name Service', 'FIS': 'Stafi', 
        'FOX': 'ShapeShift FOX Token', 'FRAX': 'Frax', 'FXS': 'Frax Share', 'GTC': 'Gitcoin', 'GYEN': 'GYEN', 'LDO': 'Lido DAO', 
        'LINK': 'ChainLink Token', 'LRC': 'LoopringCoin V2', 'LUSD': 'Liquity USD', 'MASK': 'Mask Network', 'MKR': 'Maker', 
        'OCEAN': 'Ocean Protocol', 'OP': 'Optimism', 'PEPE': 'Pepe', 'PERP': 'Perpetual Protocol', 'RAI': 'Rai Reflex Index', 
        'RGT': 'Rari Governance Token', 'SNT': 'Status', 'SNX': 'Synthetix Network Token', 'SOL': 'SOL Wormhole ', 'SUKU': 'SUKU', 
        'sUSD': 'Synth sUSD', 'SUSHI': 'Sushi', 'T': 'Threshold Network', 'TRB': 'Tellor', 'UMA': 'UMA Voting Token v1', 
        'UNI': 'Uniswap', 'USDC': 'USDCoin', 'USDC.e': 'USDCoin (Bridged from Ethereum)', 'USDT': 'Tether USD', 
        'VELO': 'Velodrome Finance', 'WBTC': 'Wrapped BTC', 'WETH': 'Wrapped Ether', 'WOO': 'WOO Network', 'YFI': 'yearn finance', 
        'ZRX': '0x Protocol Token' },

    # 这个 "ETH" 不能自动跳WETH ,172个，2/28号
    "polygon":{'1INCH': '1inch', 'AAVE': 'Aave', 'ADX': 'Ambire AdEx', 'agEUR': 'agEur', 'AGLD': 'Adventure Gold', 
        'AIOZ': 'AIOZ Network', 'ALCX': 'Alchemix', 'ALEPH': 'Aleph im', 'ALI': 'Alethea Artificial Liquid Intelligence', 
        'ALICE': 'My Neighbor Alice', 'ALPHA': 'Alpha Venture DAO', 'AMP': 'Amp', 'ANKR': 'Ankr', 'ANT': 'Aragon', 
        'APE': 'ApeCoin', 'API3': 'API3', 'ARPA': 'ARPA Chain', 'AST': 'AirSwap', 'ATA': 'Automata', 'AUDIO': 'Audius', 
        'AXS': 'Axie Infinity', 'BADGER': 'Badger DAO', 'BAL': 'Balancer', 'BAND': 'Band Protocol', 'BAT': 'Basic Attention Token', 
        'BICO': 'Biconomy', 'BIGTIME': 'Big Time', 'BLZ': 'Bluzelle', 'BNT': 'Bancor Network Token', 'BOBA': 'Boba Network', 
        'BOND': 'BarnBridge', 'BUSD': 'Binance USD', 'CELR': 'Celer Network', 'CHR': 'Chromia', 'CHZ': 'Chiliz', 'COMP': 'Compound', 
        'CQT': 'Covalent', 'CRO': 'Cronos', 'CRV': 'Curve DAO Token', 'CTSI': 'Cartesi', 'CTX': 'Cryptex Finance', 
        'CUBE': 'Somnium Space CUBEs', 'CVC': 'Civic', 'CVX': 'Convex Finance', 'DAI': 'Dai Stablecoin', 'DDX': 'DerivaDAO', 
        'DEXT': 'DexTools', 'DIA': 'DIA', 'DPI': 'DeFi Pulse Index', 'DYDX': 'dYdX', 'ELON': 'Dogelon Mars', 'ENJ': 'Enjin Coin', 
        'ENS': 'Ethereum Name Service', 'ERN': 'Ethernity Chain', 'EUROC': 'Euro Coin', 'FARM': 'Harvest Finance', 'FET': 'Fetch ai', 
        'FIS': 'Stafi', 'FORT': 'Forta', 'FORTH': 'Ampleforth Governance Token', 'FOX': 'ShapeShift FOX Token', 'FRAX': 'Frax', 
        'FTM': 'Fantom', 'FXS': 'Frax Share', 'GHST': 'Aavegotchi', 'GLM': 'Golem', 'GNO': 'Gnosis Token', 'GODS': 'Gods Unchained', 
        'GRT': 'The Graph', 'GTC': 'Gitcoin', 'GUSD': 'Gemini Dollar', 'GYEN': 'GYEN', 'HOPR': 'HOPR', 'IDEX': 'IDEX', 
        'ILV': 'Illuvium', 'IMX': 'Immutable X', 'INDEX': 'Index Cooperative', 'INJ': 'Injective', 'INV': 'Inverse Finance', 
        'IOTX': 'IoTeX', 'JASMY': 'JasmyCoin', 'KEEP': 'Keep Network', 'KNC': 'Kyber Network Crystal', 'KP3R': 'Keep3rV1', 
        'LCX': 'LCX', 'LDO': 'Lido DAO', 'LINK': 'ChainLink Token', 'LOKA': 'League of Kingdoms', 'LOOM': 'Loom Network', 
        'LPT': 'Livepeer', 'LQTY': 'Liquity', 'LRC': 'LoopringCoin V2', 'LUSD': 'Liquity USD', 'MANA': 'Decentraland', 
        'MASK': 'Mask Network', 'MATH': 'MATH', 'MATIC': 'Polygon', 'MCO2': 'Moss Carbon Credit', 'METIS': 'Metis', 
        'MIM': 'Magic Internet Money', 'MIR': 'Mirror Protocol', 'MKR': 'Maker', 'MLN': 'Melon', 'MONA': 'Monavale', 
        'MV': 'GensoKishi Metaverse', 'NCT': 'PolySwarm', 'NMR': 'Numeraire', 'OCEAN': 'Ocean Protocol', 
        'OGN': 'Origin Protocol', 'OMG': 'OMG Network', 'ORN': 'Orion Protocol', 'OXT': 'Orchid', 'PAXG': 'PAX Gold', 
        'PERP': 'Perpetual Protocol', 'PLA': 'PlayDapp', 'PLU': 'Pluton', 'POLS': 'Polkastarter', 'POLY': 'Polymath', 
        'POND': 'Marlin', 'POWR': 'Power Ledger', 'PRO': 'Propy', 'PRQ': 'PARSIQ', 'QNT': 'Quant', 'QUICK': 'Quickswap', 
        'RAD': 'Radicle', 'RAI': 'Rai Reflex Index', 'RARI': 'Rarible', 'RBC': 'Rubic', 'REN': 'Republic Token', 
        'REPv2': 'Reputation Augur v2', 'REQ': 'Request', 'REVV': 'REVV', 'RGT': 'Rari Governance Token', 'RLC': 'iExec RLC', 
        'RLY': 'Rally', 'RNDR': 'Render Token', 'ROOK': 'Rook', 'SAND': 'The Sandbox', 'SHIB': 'Shiba Inu', 
        'SLP': 'Smooth Love Potion', 'SNX': 'Synthetix Network Token', 'SPELL': 'Spell Token', 'STORJ': 'Storj Token', 
        'STX': 'Stox', 'SUKU': 'SUKU', 'SUPER': 'SuperFarm', 'sUSD': 'Synth sUSD', 'SUSHI': 'Sushi', 'SXP': 'Swipe', 
        'TOKE': 'Tokemak', 'TRAC': 'OriginTrail', 'TRB': 'Tellor', 'TRIBE': 'Tribe', 'TRU': 'TrueFi', 'TVK': 'The Virtua Kolect', 
        'UMA': 'UMA Voting Token v1', 'UNI': 'Uniswap', 'USDC': 'USDCoin', 'USDC.e': 'USDCoin (PoS)', 'USDT': 'Tether USD', 
        'VOXEL': 'Voxies', 'WBTC': 'Wrapped BTC', 'WCFG': 'Wrapped Centrifuge', 'WETH': 'Wrapped Ether', 'WMATIC': 'Wrapped Matic', 
        'WOO': 'WOO Network', 'XSGD': 'XSGD', 'XYO': 'XYO Network', 'YFI': 'yearn finance', 'YFII': 'DFI money', 
        'YGG': 'Yield Guild Games', 'ZRX': '0x Protocol Token'},

    #   26个，2/28号
    "base":{'ETH':'ETH','1INCH': '1inch', 'AERO': 'Aerodrome Finance', 'ALI': 'Alethea Artificial Liquid Intelligence', 
        'ARPA': 'ARPA Chain', 'BAL': 'Balancer', 'BTRST': 'Braintrust', 'cbETH': 'Coinbase Wrapped Staked ETH', 'COMP': 'Compound', 
        'CRV': 'Curve DAO Token', 'DAI': 'Dai Stablecoin', 'FARM': 'Harvest Finance', 'LUSD': 'Liquity USD', 'PRIME': 'Prime', 
        'PRO': 'Propy', 'SEAM': 'Seamlesss', 'SNX': 'Synthetix Network Token', 'SUSHI': 'Sushi', 'tBTC': 'tBTC', 
        'TRAC': 'OriginTrail', 'USDbC': 'USD Base Coin', 'USDC': 'USD Coin', 'WAMPL': 'Wrapped Ampleforth', 'WETH': 'Wrapped Ether', 
        'YFI': 'yearn finance', 'ZRX': '0x Protocol Token'},
    
    #  73个，2/28号
    "bnb":{'ETH':'ETH','1INCH': '1inch', 'AAVE': 'Aave', 'ACH': 'Alchemy Pay', 'ADX': 'Ambire AdEx', 'agEUR': 'agEur', 
        'AIOZ': 'AIOZ Network', 'ALEPH': 'Aleph im', 'ALICE': 'My Neighbor Alice', 'ALPHA': 'Alpha Venture DAO', 'ANKR': 'Ankr', 
        'ARPA': 'ARPA Chain', 'ATA': 'Automata', 'AXL': 'Axelar', 'AXS': 'Axie Infinity', 'BLZ': 'Bluzelle', 'BUSD': 'Binance USD', 
        'C98': 'Coin98', 'CHR': 'Chromia', 'CLV': 'Clover Finance', 'COMP': 'Compound', 'COVAL': 'Circuits of Value', 
        'CTSI': 'Cartesi', 'DAI': 'Dai Stablecoin', 'DAR': 'Mines of Dalarnia', 'DEXT': 'DexTools', 'DIA': 'DIA', 'DREP': 'Drep', 
        'DYP': 'DeFi Yield Protocol', 'ELON': 'Dogelon Mars', 'FARM': 'Harvest Finance', 'FET': 'Fetch ai', 'FRAX': 'Frax', 
        'FTM': 'Fantom', 'FXS': 'Frax Share', 'GAL': 'Project Galaxy', 'HFT': 'Hashflow', 'HIGH': 'Highstreet', 'INJ': 'Injective', 
        'JUP': 'Jupiter', 'LINK': 'ChainLink Token', 'MASK': 'Mask Network', 'MATH': 'MATH', 'MATIC': 'Polygon', 
        'MC': 'Merit Circle', 'METIS': 'Metis', 'MIM': 'Magic Internet Money', 'MIR': 'Mirror Protocol', 'MULTI': 'Multichain', 
        'NEST': 'Nest Protocol', 'PERP': 'Perpetual Protocol', 'POLS': 'Polkastarter', 'PRQ': 'PARSIQ', 'PSTAKE': 'pSTAKE Finance', 
        'REVV': 'REVV', 'SOL': 'SOL Wormhole ', 'STG': 'Stargate Finance', 'SUPER': 'SuperFarm', 'SUSHI': 'Sushi', 
        'SWFTC': 'SWFTCOIN', 'SXP': 'Swipe', 'SYN': 'Synapse', 'TIME': 'ChronoTech', 'TLM': 'Alien Worlds', 
        'UNFI': 'Unifi Protocol DAO', 'UNI': 'Uniswap', 'UPI': 'Pawtocol', 'USDC': 'USDCoin', 'USDT': 'Tether USD', 
        'WBNB': 'Wrapped BNB', 'WETH': 'Wrapped Ether', 'WOO': 'WOO Network', 'XCN': 'Chain'},

    #  显示是39个，实际多了一个ETH, 2/28号  
    "avalanche":{'ETH':'ETH','1INCH': '1inch', 'AAVE': 'Aave', 'agEUR': 'agEur', 'ALPHA': 'Alpha Venture DAO', 'ANKR': 'Ankr', 
        'AXL': 'Axelar', 'BAT': 'Basic Attention Token', 'BUSD': 'Binance USD', 'COMP': 'Compound', 'CTSI': 'Cartesi', 
        'DAI.e': 'DAI.e Token', 'DYP': 'DeFi Yield Protocol', 'EURC': 'Euro Coin', 'FRAX': 'Frax', 'FXS': 'Frax Share', 
        'GMX': 'GMX', 'GRT': 'The Graph', 'LINK': 'ChainLink Token', 'MIM': 'Magic Internet Money', 'MKR': 'Maker', 
        'MULTI': 'Multichain', 'RAI': 'Rai Reflex Index', 'SNX': 'Synthetix Network Token', 'SOL': 'SOL Wormhole ', 
        'SPELL': 'Spell Token', 'STG': 'Stargate Finance', 'SUSHI': 'Sushi', 'SYN': 'Synapse', 'UMA': 'UMA Voting Token v1', 
        'UNI.e': 'UNI.e Token', 'USDC': 'USDC Token', 'USDT': 'Tether USD', 'WAVAX': 'Wrapped AVAX', 'WBTC': 'Wrapped BTC', 
        'WETH': 'Wrapped Ether', 'WOO': 'WOO Network', 'YFI': 'yearn finance', 'ZRX': '0x Protocol Token'},
    
    #  显示是4个，实际多了一个ETH, 2/28号 
    "celo":{'ETH':'ETH','BTC': 'Wrapped Bitcoin', 'CELO': 'Celo', 'USDC': 'USDCoin', 'WETH': 'Wrapped Ether'}
    
    }