
pancake_currencies = {
    # ethereum, 68 个币,3/5
    "ethereum":{'ETH': 'Ether', 'agEUR': 'agEUR', 'AIOZ': 'AIOZ Network', 'ALCX': 'Alchemix', 'alETH': 'Alchemix ETH', 
        'ankrETH': 'Ankr Staked ETH', 'APE': 'ApeCoin', 'AXL': 'Axelar', 'BLUR': 'Blur', 'Bonk': 'Bonk', 'BTRFLY': 'BTRFLY', 
        'BUSD': 'Binance USD', 'CAKE': 'PancakeSwap Token', 'CANTO': 'Canto', 'CAPS': 'Capsule Coin', 
        'cbETH': 'Coinbase Wrapped Staked ETH', 'CRV': 'Curve DAO Token', 'CVX': 'Convex Token', 'CYBER': 'CyberConnect', 
        'DAI': 'Dai Stablecoin', 'DYDX': 'dYdX', 'ENS': 'Ethereum Name Service', 'ETHx': 'ETHx', 'FET': 'Fetch', 
        'frxETH': 'Frax Ether', 'FUSE': 'Fuse Token', 'FXS': 'Frax Share', 'ID': 'SPACE ID', 'INSP': 'Inspect', 
        'LDO': 'Lido DAO Token', 'LINK': 'ChainLink Token', 'MASK': 'Mask Network', 'MATIC': 'Matic Token', 'memecoin': 'MEME', 
        'mstETH': 'mstETH', 'mswETH': 'mswETH', 'ORDS': 'Ordiswap', 'OSAK': 'Osaka Protocol', 'PANDORA': 'Pandora', 
        'PENDLE': 'Pendle', 'PEPE': 'Pepe', 'PIXEL': 'PIXEL', 'pxETH': 'Pirex Ether', 'PYUSD': 'PayPal USD', 'rETH': 'Rocket Pool ETH', 
        'RNDR': 'Render Token', 'ROCI': 'RociFi', 'RPL': 'Rocket Pool', 'SDAO': 'Singularity Dao', 'SDT': 'Stake DAO Token', 
        'SNX': 'Synthetix Network Token', 'STG': 'StargateToken', 'swETH': 'swETH', 'TUSD': 'TrueUSD', 'unshETH': 'unshETH Ether', 
        'USDC': 'USD Coin', 'USDT': 'Tether USD', 'USH': 'unshETHing_Token', 'wBETH': 'Wrapped Binance Beacon ETH', 
        'WBTC': 'Wrapped BTC', 'weETH': 'Wrapped eETH', 'WETH': 'Wrapped Ether', 'WLD': 'Worldcoin', 'WNCG': 'Wrapped NCG', 
        'WOM': 'Wombat Token', 'WOO': 'Wootrade Network', 'wstETH': 'Wrapped liquid staked Ether 2.0', 'XRGB': 'XRGB'},

    # bnb, 390 个币,3/5
    "bnb":{'BNB': 'Binance Chain Native Token', '8PAY v2': '8PAY Network v2', 'ACE': 'ACEToken', 'ACH': 'Alchemy Token', 
           'ADA': 'Cardano Token', 'ADX': 'AdEx Network', 'agEUR': 'agEUR', 'AI': 'Any Inu', 'AIOZ': 'AIOZ Network', 
           'AITECH': 'AITECH', 'ALICE': 'My Neigbor Alice', 'ALPA': 'AlpaToken', 'ALPACA': 'Alpaca', 'ALPHA': 'AlphaToken', 
           'AMPL': 'Ampleforth', 'ANKR': 'Ankr', 'ankrBNB': 'Ankr Staked BNB', 'ankrETH': 'Ankr Staked ETH', 'ANTEX': 'Antex', 
           'anyMTLX': 'anyMTLX', 'AOG': 'AgeOfGods', 'APE': 'ApeCoin', 'APX': 'ApolloX Token', 'APYS': 'APYSwap', 'Arbitrum': 'ARB', 
           'ARENA': 'ESPL ARENA', 'ARPA': 'ARPA', 'ARV': 'ARIVA', 'ASR': 'AS Roma', 'ATA': 'Automata', 'ATM': 'Atletico de Madrid', 
           'ATOM': 'Cosmos Token', 'AUTO': 'AUTOv2', 'AXL': 'Axelar', 'axlUSDC': 'Axelar Wrapped USDC', 'AXS': 'Axie Infinity Shard', 
           'BABYCAKE': 'BabyCake', 'BAKE': 'Bakery Token', 'bALBT': 'AllianceBlock', 'BAND': 'BAND Protocol Token', 
           'BAT': 'Basic Attention Token', 'BATH': 'Battle Hero', 'bBADGER': 'bBADGER', 'BBT': 'BitBook', 'bCFX': 'Conflux', 
           'BCH': 'Bitcoin Cash Token', 'BCOIN': 'Bomb Crypto', 'bDIGG': 'bDIGG', 'BDO': 'bDollar', 'BEL': 'Bella Protocol', 
           'BELT': 'Belt', 'BETA': 'Beta Finance', 'BETH': 'Beacon ETH', 'BFI': 'b.earnfi', 'BIFI': 'Beefy.finance', 'BLK': 'BLINk', 
           'BMON': 'Binamon', 'bMXX': 'Multiplier', 'BNBx': 'Liquid Staking BNB', 'BNX': 'BinaryX', 'BONDLY': 'Bondly', 
           'Bonk': 'Bonk', 'BORING': 'BoringDAO', 'BP': 'BunnyPark', 'bROOBEE': 'ROOBEE', 'BRY': 'Berry', 
           'BSCDEFI': 'BSC Ecosystem Defi blue chips', 'BSCPAD': 'BSCPad', 'BSCX': 'BSCEX', 'BSW': 'Biswap', 'BTCB': 'BTCB Token', 
           'BTCST': 'Standard BTC Hashrate Token', 'BTR': 'Bittrue', 'BTT': 'Bittorrent', 'BTTOLD': 'Bittorrent Old', 
           'BUNNY': 'Bunny Token', 'BURGER': 'Burger Swap', 'BUSD': 'BUSD Token', 'BUX': 'BUX', 'C98': 'Coin98', 
           'CAKE': 'PancakeSwap Token', 'CAPS': 'Capsule Coin', 'CART': 'CryptoArt.ai', 'CEEK': 'CEEK', 'CGG': 'ChainGuardians', 
           'CGPT': 'ChainGPT', 'CHAMP': 'Ultimate Champions Token', 'CHESS': 'Tranchess', 'CHR': 'Chromia', 'CKP': 'Cakepie', 
           'CO': 'CO', 'COMP': 'Compound Finance', 'COS': 'Contentos', 'CREAM': 'Cream', 'CSIX': 'Carbon', 'CTK': 'CertiK Token', 
           'CVP': 'Concentrated Voting Power', 'CYBER': 'CyberConnect', 'CYC': 'Cyclone', 'DAI': 'Binance Pegged DAI', 
           'DAR': 'Mines of Dalarnia', 'DCK': 'DexCheck', 'DEFI': 'DeFi', 'DEGO': 'Dego.Finance', 'DERI': 'Deri', 'DEXE': 'DeXe', 
           'DFD': 'DefiDollar DAO', 'DFT': 'DFuture', 'DG': 'Decentral Games', 'DITTO': 'Ditto', 'DKT': 'Duelist King', 
           'DLP': 'WBNB-RDNT Pancake LP', 'DMAIL': 'Dmail Network', 'DODO': 'Dodo', 'DOGE': 'Dogecoin', 'DOT': 'Polkadot Token', 
           'DPT': 'Diviner Protocol', 'DUET': 'Duet Governance Token', 'DUSK': 'Dusk', 'DVI': 'Dvision Network', 'EDU': 'EDU Coin', 
           'EGLD': 'Elrond', 'ELON': 'Dogelon Mars', 'EOS': 'EOS Token', 'EPS': 'Ellipsis', 'EQB': 'Equilibria Token', 
           'ERA': 'Era Token', 'ERTHA': 'Ertha Token', 'esRDNT': 'Radpie esRDNT', 'ETERNAL': 'CryptoMines Eternal', 
           'ETH': 'Ethereum Token', 'EZ': 'Easy V2', 'FDUSD': 'First Digital USD', 'FIGHT': 'Fight Token', 'FIL': 'Filecoin', 
           'FINA': 'Defina Finance', 'FINE': 'Refinable', 'FOR': 'ForTube', 'FORM': 'Formation Finance', 'FRONT': 'Frontier Token', 
           'FROYO': 'Froyo', 'FUEL': 'Fuel', 'FUSE': 'Fuse Token', 'GAL': 'Galxe', 'GEAR': 'MetaGear Token', 'GM': 'GoldMiner', 
           'GMEE': 'GAMEE', 'GMI': 'Gamifi', 'GMT': 'Green Metaverse Token', 'GQ': 'Galactic Quadrant', 'GTAI': 'GT Protocol', 
           'GUM': 'Gourmet Galaxy', 'HAI': 'Hacken', 'HAKKA': 'Hakka Finance', 'HAPPY': 'HappyFans', 'HARD': 'HARD', 
           'Helmet': 'Helmet.insure', 'HERO': 'MetaHero', 'HFT': 'Hashflow', 'HGET': 'Hedget', 'HIGH': 'Highstreet Token', 
           'HOO': 'Hoo', 'HOOK': 'Hook Token', 'HOOP': 'Chibi Dinos', 'HOTCROSS': 'Hot Cross Token', 'HTB': 'Hotbit', 
           'HTD': 'HeroesTD', 'HUAHUA': 'Chihuahua native asset', 'HZN': 'Horizon Protocol', 'ID': 'SPACE ID Token', 
           'IDIA': 'Impossible Decentralized Incubator', 'IF': 'Impossible Finance', 'INJ': 'Injective Protocol', 'INSP': 'INSPECT', 
           'INSUR': 'Bsc-Peg INSUR Token', 'IOTX': 'IoTeX', 'IRL': 'Rebase', 'JASMY': 'JasmyCoin', 'JGN': 'Juggernaut Finance', 
           'JUV': 'Juventus', 'KALM': 'Kalmar', 'KART': 'Dragon Kart', 'KAVA': 'KAVA', 'KRS': 'Kingdom Raids', 'KTN': 'Kattana', 
           'KUJI': 'Kujira native asset', 'KUN': 'Qian Governance Token', 'LAZIO': 'FC Lazio Fan Token', 
           'LGO': 'Level Governance Token', 'LIEN': 'Lien', 'LIGHT': 'Lightning', 'LINA': 'Linear Finance', 'LINK': 'ChainLink Token', 
           'lisUSD': 'Lista USD', 'LIT': 'Litentry', 'LMT': 'Lympo Market Token', 'LOA': 'League Of Ancients', 'LOOKS': 'LooksRare', 
           'LTC': 'Litecoin Token', 'LTO': 'LTO Network', 'lUSD': 'lUSD', 'LVL': 'Level Token', 'mAMZN': 'Mirror AMZN Token', 
           'MANA': 'Decentraland', 'MANTA': 'Manta', 'MARSH': 'Unmarshal', 'MASK': 'Mask Network', 'MATH': 'Math', 'MBL': 'MovieBloc', 
           'MBOX': 'Mobox', 'MBX': 'MARBLEX on BNB', 'mCAKE': 'mCake Token', 'MCB': 'MCDEX', 'mCOIN': 'Mirror COIN', 
           'MCRN': 'MacaronSwap', 'mDLP': 'Magpie locked DLP', 'Metis': 'Metis Token', 'mGOOGL': 'Mirror GOOGL Token', 
           'MGP': 'Magpie Token', 'MHUNT': 'MetaShooter', 'MIR': 'Mirror Finance', 'MIX': 'Mix', 'MIXOLD': 'MixMarvel Token Old', 
           'mNFLX': 'Mirror NFLX Token', 'MONI': 'Monsta Infinite', 'mPENDLE': 'mPendle', 'MTRG': 'Meter', 'mTSLA': 'Mirror TSLA Token',
            'MUBI': 'MUBI', 'MX': 'MX Token', 'NABOX': 'Nabox Token', 'NAOS': 'NAOS Finance', 'NBT': 'NanoByte Token', 
            'NFP': 'NFPrompt Token', 'NFT': 'APENFT', 'NMT': 'NetMind Token', 'NRV': 'Nerve Finance', 'NULS': 'Nuls', 
            'NVT': 'NerveNetwork', 'O3': 'O3 Swap', 'ODDZ': 'Oddz', 'OG': 'OG', 'OIN': 'Oin Finance', 'OLE': 'OpenLeverage', 
            'ONE': 'Harmony One', 'ONT': 'Ontology Token', 'OP': 'Optimism', 'ORBS': 'Token Orbs', 'ordi': 'ordi', 
            'OSAK': 'Osaka Protocol', 'OVN': 'OVN', 'pBTC': 'pBTC', 'pCWS': 'PolyCrowns', 'PEAK': 'PEAKDEFI', 'PEEL': 'Meta Apes Peel',
            'PENDLE': 'Pendle', 'PEOPLE': 'ConstitutionDAO', 'PEPE': 'Pepe', 'PERL': 'Perlin X', 'PEX': 'PearDAO', 
            'PHA': 'Phala Network', 'PLANET': 'PLANET', 'PLAY': 'PLAY', 'PMON': 'Polkamon', 'PNP': 'Penpie Token', 'PNT': 'PNT', 
            'pOPEN': 'pTokens OPEN', 'PORTO': 'FC Porto Fan Token', 'POTS': 'Moonpot', 'PRIMAL': 'PRIMAL Token', 
            'PRL': 'Parallel Token', 'PROM': 'Prometeus', 'PROS': 'Prosper', 'PSG': 'Paris Saint-Germain', 'PSTAKE': 'pStake Finance', 
            'QBT': 'Qubit Token', 'QI': 'BENQI', 'QKC': 'QuarkChain Token', 'QSD': 'QIAN second generation dollar', 
            'QUIDD': 'Quidd Token', 'RABBIT': 'Rabbit Finance', 'RACA': 'Radio Caca V2', 'RAMP': 'Ramp DEFI', 'rBNB': 'StaFi rBNB', 
            'RDNT': 'Radiant', 'RDP': 'Radpie', 'REEF': 'Reef', 'renBTC': 'renBTC', 'REVV': 'REVV', 'RFOX': 'RFOX', 
            'RPG': 'RangersProtocolGas', 'RPGOLD': 'Rangers Protocol Old', 'rUSD': 'rUSD', 'SABLE': 'SABLE', 'SAND': 'The Sandbox', 
            'SANTOS': 'FC Santos Fan Token', 'sats': 'sats', 'SD': 'Stader (Wormhole)', 'SDAO': 'Singularity Dao', 
            'sdCAKE': 'Stake DAO CAKE', 'SFP': 'SafePal Token', 'SFUND': 'Seedify', 'SHEESHA': 'Sheesha Finance', 
            'SHELL': 'Meta Apes Shell', 'SIS': 'Symbiosis', 'SKILL': 'CryptoBlades Skill Token', 'slisBNB': 'Staked Lista BNB', 
            'SOL': 'SOLANA', 'SPARTA': 'SPARTAN PROTOCOL TOKEN', 'SPIN': 'Spintop', 'SPS': 'Splintershards', 'SQUAD': 'Token SQUAD', 
            'STG': 'StargateToken', 'stkBNB': 'Staked BNB', 'SUSHI': 'Sushi', 'SUTER': 'Suterusu', 'SWAMP': 'Swampy', 'SWG': 'SWGToken', 'SWINGBY': 'Swingby', 'SWTH': 'Carbon Protocol', 'SXP': 'Swipe', 'tBTC': 'Tau Bitcoin', 'tDOGE': 'Tau DOGE', 'TEM': 'TemplarDAO', 'TEN': 'Tenet', 'THG': 'Thetan Gem', 'TINC': 'Tiny Coin', 'TITAN': 'TitanSwap', 'TKO': 'TokoCrypto', 'TLM': 'Alien Worlds', 'TLOS': 'Telos', 
            'TPT': 'TokenPocket', 'TRADE': 'Unitrade', 'TRIVIA': 'Trivian Token', 'TRX': 'Tron', 'TT': 'ThunderCore', 'TUSD': 'TrueUSD', 
            'TUSDOLD': 'True USD Old', 'TWT': 'Trust Wallet', 'TXL': 'Tixl', 'UBXT': 'UpBots', 'UNFI': 'Unifi Token', 'UNI': 'Uniswap', 
            'unshETH': 'unshETH Ether', 'UNW': 'Uniwhale Token', 'USDC': 'Binance Pegged USD Coin', 'USDT': 'Tether USD', 
            'USDV': 'USDV', 'USH': 'unshETHing_Token', 'UST': 'UST Token', 'VAI': 'VAI Stablecoin', 'VET': 'VeChain', 
            'VRT': 'Venus Reward Token', 'WATCH': 'Yieldwatch', 'WAULTx': 'Wault', 'wBETH': 'Wrapped Binance Beacon ETH', 
            'WBNB': 'Wrapped BNB', 'WELL': 'BitWell Token', 'WEX': 'WaultSwap', 'WIN': 'WINk', 'WMASS': 'Wrapped MASS', 
            'WMX': 'Wombex Token', 'WNCG': 'WrappedNCG', 'WOM': 'Wombat Token', 'WOO': 'Wootrade', 'WOOP': 'Woonkly Power', 
            'wROSE': 'Wrapped ROSE', 'WSG': 'Wall Street Games', 'WZRD': 'Wizardia Coin', 'xALGO': 'Governance xAlgo', 
            'XCAD': 'XCAD Token', 'XCN': 'Chain', 'XCV': 'XCarnival', 'XED': 'Exeedme', 'XEND': 'XEND', 'xMARK': 'xMARK', 
            'XMS': 'Mars Ecosystem', 'XRGB': 'XRGB', 'XRP': 'XRP Token', 'XTZ': 'Tezos Token', 'XVS': 'Venus Token', 
            'XWG': 'X World Games', 'YEL': 'YEL', 'YFI': 'yearn.finance', 'YFII': 'YFII.finance Token', 'ZBC': 'ZEBEC', 
            'ZEC': 'Zcash Token', 'ZEE': 'ZeroSwapToken', 'ZIL': 'Zilliqa', 'ZOO': 'ZOO Crypto World'},

    # opbnb, 8 个币,3/5
    "opbnb":{'BNB': 'Binance Chain Native Token', 'ALP': 'ApolloX LP', 'BTCB': 'BTCB Token', 'CAKE': 'PancakeSwap Token', 
             'ETH': 'Ethereum Token', 'FDUSD': 'First Digital USD', 'USDT': 'Tether USD', 'WBNB': 'Wrapped BNB'},

    # zksync, 14 个币,3/5
    "zksync":{'ETH': 'Ether', 'BUSD': 'Binance USD', 'CAKE': 'PancakeSwap Token', 'DAI': 'DAI Stablecoin', 'MEOW': 'Zeek Coin', 
          'rETH': 'Rocket Pool ETH', 'TES': 'TES', 'USD+': 'USD Plus', 'USDC': 'USD Coin', 'USDT': 'Tether USD', 'WBTC': 'Wrapped BTC', 
          'WETH': 'Wrapped Ether', 'WETH.e': 'Wrapped Ether Native Bridge', 'wstETH': 'Wrapped liquid staked Ether 2.0'},

    # base, 78 个币,3/5
    "base":{'ETH': 'Ether', '1INCH': '1INCH Token', 'ALI': 'Artificial Liquid Intelligence Token', 
        'AMKT': 'Alongside Crypto Market Index', 'ARIA20': 'ARIANEE', 'ARPA': 'ARPA Token', 'axlUSDC': 'Axelar Wrapped USDC', 
        'BAL': 'Balancer', 'BKN': 'Brickken', 'BLUE': 'BlueSwap', 'BTRST': 'BTRST', 'bwAJNA': 'Burn Wrapped AJNA', 
        'CAKE': 'PancakeSwap Token', 'cbETH': 'Coinbase Wrapped Staked ETH', 'COC': 'CryptoOracle Collective', 'COMP': 'Compound', 
        'CRV': 'Curve DAO Token', 'crvUSD': 'Curve.Fi USD Stablecoin', 'D2D': 'Prime', 'DAI': 'Dai Stablecoin', 'DOG': 'The Doge NFT', 
        'DOLA': 'Dola USD Stablecoin', 'DRODEC': 'DRODEC', 'FARM': 'FARM Reward Token', 'FLUX': 'Flux', 'GRG': 'Rigo Token', 
        'GROW': 'ValleyDAO Token', 'HAN': 'HanChain', 'HANeP': 'HANePlatform', 'HOP': 'Hop', 'iFARM': 'iFARM', 'INFC': 'Infected', 
        'ISK': 'ISKRA TOKEN', 'JRT': 'Jarvis Reward Token', 'KNC': 'Kyber Network Crystal v2', 'KOMPETE': 'KOMPETE Token', 
        'LUSD': 'LUSD Stablecoin', 'MBS': 'MBS', 'MET': 'Metronome2', 'MPWR': 'Empower Token', 'MTA': 'Meta', 'NFD': 'Feisty Doge', 
        'NFTE': 'NFTEarthOFT', 'NOGS': 'Noggles', 'PIP': 'PIP', 'PLG': 'Plague', 'PNDR': 'Ponder', 'POOL': 'PoolTogether', 
        'PRIME': 'Prime', 'PRO': 'Propy', 'RDMP': 'Redemption Finance', 'rETH': 'Rocket Pool ETH', 'RPL': 'Rocket Pool Protocol', 
        'RSR': 'Reserve Rights', 'SABLE': 'SABLE', 'SEAM': 'Seamless', 'send': 'Send Token', 'SIPHER': 'Sipher Token', 
        'SNX': 'Synthetix', 'SOFI': 'Rai.Finance', 'SPOT': 'SPOT', 'SUS': 'Sustainable Growth', 'SUSHI': 'SushiToken', 
        'tbtc': 'Base tBTC v2', 'TETU': 'Tetu Token', 'THALES': 'Optimistic Thales Token', 'TKN': 'Token Name Service', 
        'TOWER': 'TOWER', 'TRAC': 'Trace Token', 'USDbC': 'USD Base Coin', 'USDC': 'USD Coin', 'WAMPL': 'Wrapped Ampleforth', 
        'weETH': 'Wrapped eETH', 'WETH': 'Wrapped Ether', 'wOpenX': 'OpenX Optimism', 'wstETH': 'Wrapped liquid staked Ether 2.0', 
        'YFI': 'yearn.finance', 'ZRX': '0x Protocol Token'},

    # aptos, 25 个币,3/5
    "aptos":{'APT': 'Aptos Coin', 'amAPT': 'Amnis Finance', 'BLT': 'Blocto Token', 'CAKE': 'PancakeSwap Token', 
        'ceBNB': 'Celer - Binance Coin', 'ceBUSD': 'Celer - Binance USD', 'ceDAI': 'Celer - Dai Stablecoin', 
        'ceUSDC': 'Celer - USD Coin', 'ceUSDT': 'Celer - Tether USD', 'ceWBTC': 'Celer - Wrapped BTC', 
        'ceWETH': 'Celer - Wrapped Ether', 'GUI': 'GUI INU', 'lzUSDC': 'LayerZero - USD coin', 'lzUSDT': 'LayerZero - Tether USD', 
        'lzWETH': 'LayerZero - Wrapped Ether', 'MEE': 'Meeiro', 'MOJO': 'Mojito', 'MOVE': 'BlueMove', 'stAPT': 'Ditto Staked Aptos', 
        'tAPT': 'Tortuga Staked APT', 'THL': 'Thala Token', 'whBUSD': 'Wormhole - Binance USD', 'whUSDC': 'Wormhole - USD Coin', 
        'whUSDT': 'Wormhole - Tether USD', 'whWETH': 'Wormhole - Wrapped Ether'},

}


